// lib/professions.ts

export const PROFESSIONS: Record<string, string[]> = {
  'I': [
    
    
    
    'Diseño de joyas',
    'Artes plásticas (pintura, escultura, danza, teatro, artesanía, cerámica)',
    'Dibujo publicitario',
    'Restauración y museología',
    'Modelaje',
    'Gestión gráfica y publicitaria',
    'Locución y publicidad',
    'Camarógrafo/a',
    'Arte industrial',
    'Producción audiovisual y multimedia',
    'Comunicación y producción en radio y televisión',
    'Diseño del paisaje',
    'Cine y video',
    'Comunicación escénica para televisión',
  
  ],
  'II': [
    'Psicología',
    'Trabajo social',
    'Idiomas',
    'Educación internacional',
    'Historia y geografía',
    'Periodismo',
    'Periodismo digital',
    'Derecho',
    'Ciencias políticas',
    'Sociología',
    'Antropología',
    'Arqueología',
    'Gestión social y desarrollo',
    'Consejería familiar',
    'Comunicación y publicidad',
    'Administración educativa',
    'Educación especial',
    'Psicopedagogía',
    'Estimulación temprana',
    'Traducción simultánea',
    'Lingüística',
    'Educación de párvulos',
    'Bibliotecología',
    'Museología',
    'Relaciones internacionales y diplomacia',
    'Comunicación social con énfasis en márquetin y gestión de empresas',
    'Redacción creativa y publicitaria',
    'Relaciones públicas y comunicación organizacional',
    'Hotelería y turismo',
    'Teología',
    'Institución sacerdotal',
  ],
  'III': [
    'Administración de empresas',
    'Contabilidad',
    'Auditoría',
    'Ventas',
    'Márquetin estratégico',
    'Gestión y negocios internacionales',
    'Gestión empresarial',
    'Gestión financiera',
    'Ingeniería comercial',
    'Comercio exterior',
    'Banca y finanzas',
    'Gestión de recursos humanos',
    'Comunicaciones integradas en márquetin',
    'Administración de empresas ecoturísticas y de hospitalidad',
    'Ciencias económicas y financieras',
    'Administración y ciencias políticas',
    'Ciencias empresariales',
    'Comercio electrónico',
    'Emprendimiento',
    'Gestión de organismos públicos (municipios, ministerios, etc.)',
    'Gestión de centros educativos',
  ],
  'IV': [
    'Ingeniería en sistemas computacionales',
    'Geología',
    'Ingeniería civil',
    'Arquitectura',
    'Electrónica',
    'Telemática',
    'Telecomunicaciones',
    'Ingeniería mecatrónica (robótica)',
    'Imagen y sonido',
    'Minas, petróleo y metalurgia',
    'Ingeniería mecánica',
    'Ingeniería industrial',
    'Física',
    'Matemáticas aplicadas',
    'Ingeniería en estadística',
    'Ingeniería automotriz',
    'Biotecnología ambiental',
    'Ingeniería geográfica',
    'Carreras militares (marina, aviación, ejército)',
    'Ingeniería en costas y obras portuarias',
    'Estadística informática',
    'Programación y desarrollo de sistemas',
    'Tecnología en informática educativa',
    'Astronomía',
    'Ingeniería en ciencias geográficas y desarrollo sustentable',
  ],
  'V': [
    'Biología',
    'Bioquímica',
    'Farmacia',
    'Biología marina',
    'Bioanálisis',
    'Biotecnología',
    'Ciencias ambientales',
    'Zootecnia',
    'Veterinaria',
    'Nutrición y estética',
    'Cosmetología',
    'Dietética y estética',
    'Medicina',
    'Obstetricia',
    'Urgencias médicas',
    'Odontología',
    'Enfermería',
    'Tecnología, oceanografía y ciencias ambientales',
    'Agronomía',
    'Horticultura y fruticultura',
    'Ingeniería de alimentos',
    'Gastronomía',
    'Cultura física, deportes y rehabilitación',
    'Gestión ambiental',
    'Ingeniería ambiental',
    'Optometría',
    'Homeopatía',
    'Reflexología',
  ],
};