// lib/professions.ts

export interface Activity {
  id: string;
  description: string;
}

export interface Profession {
  name: string;
  activities: Activity[];
}

export const PROFESSIONS: Record<string, Profession[]> = {
  'I': [
    {
      name: 'Diseño gráfico',
      activities: [
        { id: '1', description: 'Crear logos y marcas visuales para empresas' },
        { id: '2', description: 'Diseñar layouts para publicaciones y revistas' },
        { id: '3', description: 'Producir gráficos para redes sociales e internet' },
        { id: '4', description: 'Editar y retocar fotografías profesionalmente' },
        { id: '5', description: 'Trabajar con tipografía y composición visual' },
        { id: '6', description: 'Crear presentaciones visuales atractivas' },
        { id: '7', description: 'Diseñar envases y embalajes' },
        { id: '8', description: 'Producir materiales de marketing impreso' },
        { id: '9', description: 'Colaborar con clientes para entender sus necesidades' },
        { id: '10', description: 'Mantenerse actualizado con tendencias de diseño' },
      ],
    },
    {
      name: 'Diseño y decoración de interiores',
      activities: [
        { id: '1', description: 'Planificar la distribución de espacios' },
        { id: '2', description: 'Seleccionar colores y materiales decorativos' },
        { id: '3', description: 'Proponer mobiliario y elementos funcionales' },
        { id: '4', description: 'Crear planos y visualizaciones 3D' },
        { id: '5', description: 'Trabajar con presupuestos y proveedores' },
        { id: '6', description: 'Supervisar la instalación y montaje' },
        { id: '7', description: 'Asesorar a clientes sobre tendencias y estilos' },
        { id: '8', description: 'Resolver problemas de iluminación y funcionalidad' },
        { id: '9', description: 'Hacer visitas de inspección a proyectos' },
        { id: '10', description: 'Presentar propuestas creativas a clientes' },
      ],
    },
    {
      name: 'Diseño de jardines',
      activities: [
        { id: '1', description: 'Seleccionar plantas y flores adecuadas' },
        { id: '2', description: 'Diseñar layouts y distribuciones de espacios verdes' },
        { id: '3', description: 'Planificar sistemas de riego' },
        { id: '4', description: 'Crear caminos, terrazas y estructuras paisajísticas' },
        { id: '5', description: 'Considerar factores climáticos y de sostenibilidad' },
        { id: '6', description: 'Hacer presupuestos de materiales y mano de obra' },
        { id: '7', description: 'Presentar diseños visuales a clientes' },
        { id: '8', description: 'Supervisar la instalación del jardín' },
        { id: '9', description: 'Recomendar mantenimiento y cuidados' },
        { id: '10', description: 'Crear espacios que mejoren la calidad de vida' },
      ],
    },
    {
      name: 'Diseño de modas',
      activities: [
        { id: '1', description: 'Crear bocetos y diseños de prendas' },
        { id: '2', description: 'Investigar tendencias de moda global' },
        { id: '3', description: 'Seleccionar telas, texturas y materiales' },
        { id: '4', description: 'Hacer patrones y prototipos de ropa' },
        { id: '5', description: 'Colaborar con sastre y confeccionistas' },
        { id: '6', description: 'Organizar desfiles de moda' },
        { id: '7', description: 'Trabajar con modelos para ajustes y pruebas' },
        { id: '8', description: 'Presentar colecciones a compradores' },
        { id: '9', description: 'Gestionar presupuestos de producción' },
        { id: '10', description: 'Expresar creatividad e identidad a través del diseño' },
      ],
    },
    {
      name: 'Fotografía',
      activities: [
        { id: '1', description: 'Capturar momentos en eventos y ocasiones' },
        { id: '2', description: 'Editar y retocar fotografías en software especializado' },
        { id: '3', description: 'Manejar cámaras profesionales y equipo técnico' },
        { id: '4', description: 'Trabajar con iluminación y composición' },
        { id: '5', description: 'Crear portafolios de trabajos realizados' },
        { id: '6', description: 'Colaborar con clientes para conocer sus necesidades' },
        { id: '7', description: 'Fotografiar productos para catálogos' },
        { id: '8', description: 'Gestionar sesiones fotográficas' },
        { id: '9', description: 'Entregar trabajos en diferentes formatos' },
        { id: '10', description: 'Mantener equipamiento fotográfico en buen estado' },
      ],
    },
    {
      name: 'Música',
      activities: [
        { id: '1', description: 'Tocar uno o varios instrumentos musicales' },
        { id: '2', description: 'Componer y arreglar piezas musicales' },
        { id: '3', description: 'Practicar diariamente para mejorar técnica' },
        { id: '4', description: 'Presentarse ante audiencias en conciertos' },
        { id: '5', description: 'Trabajar en estudios de grabación' },
        { id: '6', description: 'Colaborar con otros músicos en proyectos' },
        { id: '7', description: 'Enseñar música a estudiantes' },
        { id: '8', description: 'Investigar estilos musicales e historia' },
        { id: '9', description: 'Producir contenido musical digital' },
        { id: '10', description: 'Expresar emociones a través de la música' },
      ],
    },
    {
      name: 'Actuación',
      activities: [
        { id: '1', description: 'Interpretar personajes en obras teatrales' },
        { id: '2', description: 'Actuar en películas, series y producciones audiovisuales' },
        { id: '3', description: 'Ensayar y memorizar diálogos largos' },
        { id: '4', description: 'Trabajar con directores en la construcción de personajes' },
        { id: '5', description: 'Hacer audiciones y castings' },
        { id: '6', description: 'Colaborar con otros actores y equipo de producción' },
        { id: '7', description: 'Manejar emocionalmente escenas difíciles o intensas' },
        { id: '8', description: 'Recibir críticas constructivas y feedback' },
        { id: '9', description: 'Promocionar proyectos a través de entrevistas' },
        { id: '10', description: 'Expresar creatividad e identidad artística' },
      ],
    },
    {
  name: 'Diseño de joyas',
  activities: [
    { id: '1', description: 'Diseñar piezas de joyería originales y funcionales' },
    { id: '2', description: 'Seleccionar materiales como metales, piedras y gemas' },
    { id: '3', description: 'Elaborar prototipos de joyas a mano o con herramientas digitales' },
    { id: '4', description: 'Trabajar con técnicas de fundición, soldadura y pulido' },
    { id: '5', description: 'Crear colecciones de joyas inspiradas en tendencias o conceptos' },
    { id: '6', description: 'Realizar bocetos y renders en programas de diseño 3D' },
    { id: '7', description: 'Colaborar con marcas o diseñadores en la producción de joyas' },
    { id: '8', description: 'Asesorar a clientes sobre estilos y materiales' },
    { id: '9', description: 'Controlar la calidad y el acabado final de las piezas' },
    { id: '10', description: 'Investigar sobre nuevas técnicas y tendencias en joyería contemporánea' },
  ],
},
{
  name: 'Artes plásticas (pintura, escultura, danza, teatro, artesanía, cerámica)',
  activities: [
    { id: '1', description: 'Expresar ideas y emociones a través de medios artísticos' },
    { id: '2', description: 'Crear obras originales en distintos soportes y materiales' },
    { id: '3', description: 'Participar en exposiciones, muestras o espectáculos' },
    { id: '4', description: 'Investigar y experimentar con nuevas técnicas artísticas' },
    { id: '5', description: 'Restaurar o conservar obras propias o ajenas' },
    { id: '6', description: 'Gestionar su propio taller o espacio creativo' },
    { id: '7', description: 'Enseñar o coordinar talleres artísticos' },
    { id: '8', description: 'Colaborar con otros artistas o instituciones culturales' },
    { id: '9', description: 'Promocionar su trabajo en ferias y redes sociales' },
    { id: '10', description: 'Mantener una producción artística constante' },
  ],
},
{
  name: 'Dibujo publicitario',
  activities: [
    { id: '1', description: 'Crear ilustraciones y bocetos para campañas publicitarias' },
    { id: '2', description: 'Diseñar piezas visuales que comuniquen mensajes de marca' },
    { id: '3', description: 'Trabajar junto a redactores y creativos publicitarios' },
    { id: '4', description: 'Realizar storyboards para anuncios y videos' },
    { id: '5', description: 'Adaptar ilustraciones a distintos formatos y plataformas' },
    { id: '6', description: 'Usar software de ilustración digital y vectorial' },
    { id: '7', description: 'Interpretar briefs y propuestas de clientes o agencias' },
    { id: '8', description: 'Desarrollar personajes o íconos visuales para marcas' },
    { id: '9', description: 'Mantener un estilo gráfico coherente con la identidad de la marca' },
    { id: '10', description: 'Actualizar su portfolio con trabajos creativos' },
  ],
},
{
  name: 'Restauración y museología',
  activities: [
    { id: '1', description: 'Conservar y restaurar obras de arte, documentos o piezas históricas' },
    { id: '2', description: 'Analizar el estado de conservación de objetos patrimoniales' },
    { id: '3', description: 'Aplicar técnicas y materiales adecuados para la restauración' },
    { id: '4', description: 'Documentar los procesos de intervención y restauración' },
    { id: '5', description: 'Colaborar con museos, archivos y centros culturales' },
    { id: '6', description: 'Diseñar exhibiciones y montajes museográficos' },
    { id: '7', description: 'Investigar sobre historia del arte y materiales antiguos' },
    { id: '8', description: 'Supervisar el almacenamiento y transporte de piezas valiosas' },
    { id: '9', description: 'Participar en proyectos de preservación del patrimonio cultural' },
    { id: '10', description: 'Cumplir normas éticas y técnicas de conservación preventiva' },
  ],
},
{
  name: 'Modelaje',
  activities: [
    { id: '1', description: 'Participar en sesiones fotográficas y desfiles de moda' },
    { id: '2', description: 'Trabajar con fotógrafos, diseñadores y maquilladores' },
    { id: '3', description: 'Posar con distintas expresiones y actitudes según la campaña' },
    { id: '4', description: 'Cuidar la postura, expresión y movimiento corporal' },
    { id: '5', description: 'Seguir las tendencias de moda y estética actual' },
    { id: '6', description: 'Representar marcas o productos en eventos y promociones' },
    { id: '7', description: 'Construir una imagen profesional y un book fotográfico' },
    { id: '8', description: 'Realizar castings y audiciones con agencias de modelos' },
    { id: '9', description: 'Colaborar en producciones audiovisuales o publicitarias' },
    { id: '10', description: 'Mantener hábitos saludables y una buena presentación personal' },
  ],
},
{
  name: 'Gestión gráfica y publicitaria',
  activities: [
    { id: '1', description: 'Planificar y coordinar campañas publicitarias visuales' },
    { id: '2', description: 'Supervisar la producción de materiales gráficos' },
    { id: '3', description: 'Diseñar estrategias de comunicación visual para empresas' },
    { id: '4', description: 'Coordinar equipos de diseño, fotografía y redacción' },
    { id: '5', description: 'Gestionar presupuestos y tiempos de entrega' },
    { id: '6', description: 'Seleccionar medios adecuados para la difusión de campañas' },
    { id: '7', description: 'Analizar resultados y efectividad de acciones publicitarias' },
    { id: '8', description: 'Mantener contacto con clientes y proveedores gráficos' },
    { id: '9', description: 'Supervisar la identidad visual de marcas y productos' },
    { id: '10', description: 'Actualizarse en tendencias y herramientas de marketing visual' },
  ],
},
{
  name: 'Locución y publicidad',
  activities: [
    { id: '1', description: 'Locutar comerciales, programas radiales o televisivos' },
    { id: '2', description: 'Modular la voz para distintos tipos de mensajes y audiencias' },
    { id: '3', description: 'Grabar y editar piezas de audio publicitarias' },
    { id: '4', description: 'Realizar presentaciones y conducción de eventos en vivo' },
    { id: '5', description: 'Preparar guiones y textos para locución' },
    { id: '6', description: 'Trabajar en estudios de radio, televisión o agencias' },
    { id: '7', description: 'Ejercitar la dicción, respiración y manejo de la voz profesional' },
    { id: '8', description: 'Interpretar distintos tonos y estilos según el producto o mensaje' },
    { id: '9', description: 'Colaborar con equipos de producción y dirección' },
    { id: '10', description: 'Actualizarse en técnicas vocales y tendencias publicitarias' },
  ],
},
{
  name: 'Camarógrafo/a',
  activities: [
    { id: '1', description: 'Operar cámaras de video en estudios o locaciones' },
    { id: '2', description: 'Seleccionar encuadres, planos y movimientos de cámara' },
    { id: '3', description: 'Trabajar con directores, productores y técnicos de iluminación' },
    { id: '4', description: 'Ajustar parámetros técnicos como foco, exposición y balance de blancos' },
    { id: '5', description: 'Filmar entrevistas, documentales, eventos o ficciones' },
    { id: '6', description: 'Montar y desmontar equipos de grabación profesional' },
    { id: '7', description: 'Mantener y cuidar el equipo de cámara y accesorios' },
    { id: '8', description: 'Colaborar en la edición y selección de material grabado' },
    { id: '9', description: 'Seguir las indicaciones del guion técnico o storyboard' },
    { id: '10', description: 'Adaptarse a diferentes entornos y condiciones de rodaje' },
  ],
},
{
  name: 'Arte industrial',
  activities: [
    { id: '1', description: 'Diseñar objetos funcionales con valor estético y práctico' },
    { id: '2', description: 'Trabajar con materiales como metal, madera, cerámica o plástico' },
    { id: '3', description: 'Crear prototipos y modelos tridimensionales' },
    { id: '4', description: 'Aplicar principios de ergonomía y sostenibilidad en el diseño' },
    { id: '5', description: 'Colaborar con ingenieros y técnicos en procesos productivos' },
    { id: '6', description: 'Investigar sobre materiales y procesos industriales innovadores' },
    { id: '7', description: 'Supervisar la producción artesanal o semiindustrial de objetos' },
    { id: '8', description: 'Desarrollar productos para el mercado y la industria cultural' },
    { id: '9', description: 'Integrar arte, técnica y funcionalidad en sus diseños' },
    { id: '10', description: 'Exponer y comercializar sus creaciones en ferias o tiendas especializadas' },
  ],
},
{
  name: 'Producción audiovisual y multimedia',
  activities: [
    { id: '1', description: 'Planificar y coordinar proyectos audiovisuales y digitales' },
    { id: '2', description: 'Gestionar recursos técnicos, humanos y presupuestarios' },
    { id: '3', description: 'Supervisar la grabación, edición y postproducción de videos' },
    { id: '4', description: 'Trabajar con guionistas, directores y equipos creativos' },
    { id: '5', description: 'Diseñar contenidos para redes sociales y plataformas digitales' },
    { id: '6', description: 'Controlar los tiempos y cronogramas de producción' },
    { id: '7', description: 'Coordinar la difusión de materiales audiovisuales' },
    { id: '8', description: 'Buscar locaciones y gestionar permisos de filmación' },
    { id: '9', description: 'Asegurar la calidad técnica y artística del producto final' },
    { id: '10', description: 'Actualizarse en nuevas tecnologías y herramientas multimedia' },
  ],
},
{
  name: 'Comunicación y producción en radio y televisión',
  activities: [
    { id: '1', description: 'Producir y coordinar programas de radio y televisión' },
    { id: '2', description: 'Organizar los recursos técnicos y humanos del equipo de producción' },
    { id: '3', description: 'Desarrollar ideas y guiones para contenidos audiovisuales' },
    { id: '4', description: 'Supervisar grabaciones, transmisiones y emisiones en vivo' },
    { id: '5', description: 'Seleccionar música, invitados y secciones del programa' },
    { id: '6', description: 'Trabajar con locutores, camarógrafos y editores' },
    { id: '7', description: 'Gestionar la programación y la parrilla de contenidos' },
    { id: '8', description: 'Coordinar la publicidad y la promoción del programa' },
    { id: '9', description: 'Adaptar los contenidos a distintos públicos y formatos' },
    { id: '10', description: 'Monitorear audiencias y evaluar el impacto comunicacional' },
  ],
},
{
  name: 'Diseño del paisaje',
  activities: [
    { id: '1', description: 'Diseñar y planificar espacios verdes y entornos naturales' },
    { id: '2', description: 'Seleccionar especies vegetales según clima y funcionalidad' },
    { id: '3', description: 'Elaborar planos y maquetas de proyectos paisajísticos' },
    { id: '4', description: 'Coordinar obras de jardinería y mantenimiento de espacios' },
    { id: '5', description: 'Integrar criterios de sustentabilidad y ecología en el diseño' },
    { id: '6', description: 'Colaborar con arquitectos y urbanistas en proyectos de espacio público' },
    { id: '7', description: 'Supervisar el uso de materiales y sistemas de riego' },
    { id: '8', description: 'Realizar relevamientos de terreno y estudios ambientales' },
    { id: '9', description: 'Asesorar a clientes sobre diseño y cuidado del paisaje' },
    { id: '10', description: 'Actualizarse en tendencias de diseño sustentable y naturalismo' },
  ],
},
{
  name: 'Cine y video',
  activities: [
    { id: '1', description: 'Escribir, dirigir o producir películas y cortometrajes' },
    { id: '2', description: 'Trabajar con cámaras, iluminación y sonido en rodajes' },
    { id: '3', description: 'Editar y montar material audiovisual en software profesional' },
    { id: '4', description: 'Coordinar equipos técnicos y artísticos durante la filmación' },
    { id: '5', description: 'Diseñar guiones y storyboards para proyectos audiovisuales' },
    { id: '6', description: 'Supervisar la postproducción y la corrección de color' },
    { id: '7', description: 'Participar en festivales y muestras de cine' },
    { id: '8', description: 'Promocionar y distribuir obras en distintas plataformas' },
    { id: '9', description: 'Colaborar en documentales, videoclips o proyectos institucionales' },
    { id: '10', description: 'Explorar nuevas narrativas visuales y tecnologías cinematográficas' },
  ],
},
{
  name: 'Comunicación escénica para televisión',
  activities: [
    { id: '1', description: 'Interpretar personajes y roles en producciones televisivas' },
    { id: '2', description: 'Trabajar la expresión corporal y vocal frente a cámara' },
    { id: '3', description: 'Leer e interpretar guiones televisivos' },
    { id: '4', description: 'Participar en ensayos y grabaciones en estudio o exteriores' },
    { id: '5', description: 'Colaborar con directores, productores y equipos técnicos' },
    { id: '6', description: 'Adaptar la actuación al lenguaje audiovisual' },
    { id: '7', description: 'Participar en programas, telenovelas, series o publicidades' },
    { id: '8', description: 'Cuidar la presencia escénica y la expresión emocional' },
    { id: '9', description: 'Desarrollar habilidades de improvisación y comunicación' },
    { id: '10', description: 'Actualizarse en técnicas actorales para medios digitales y TV' },
  ],
},
  ],
  'II': [
    {
      name: 'Psicología',
      activities: [
        { id: '1', description: 'Realizar sesiones de terapia individual con pacientes' },
        { id: '2', description: 'Evaluar y diagnosticar problemas de salud mental' },
        { id: '3', description: 'Diseñar planes de tratamiento personalizados' },
        { id: '4', description: 'Investigar nuevas técnicas y enfoques terapéuticos' },
        { id: '5', description: 'Mantener registros confidenciales de pacientes' },
        { id: '6', description: 'Trabajar en equipo multidisciplinario' },
        { id: '7', description: 'Asistir a supervisiones y formación continua' },
        { id: '8', description: 'Facilitar talleres y grupos de apoyo' },
        { id: '9', description: 'Colaborar con otros profesionales en casos complejos' },
        { id: '10', description: 'Mostrar empatía y comprensión hacia los pacientes' },
      ],
    },
    {
      name: 'Trabajo social',
      activities: [
        { id: '1', description: 'Evaluar necesidades de familias y comunidades' },
        { id: '2', description: 'Derivar a servicios sociales y recursos disponibles' },
        { id: '3', description: 'Hacer seguimiento de casos y población vulnerable' },
        { id: '4', description: 'Diseñar programas de intervención social' },
        { id: '5', description: 'Preparar informes y documentación' },
        { id: '6', description: 'Mediar en conflictos familiares' },
        { id: '7', description: 'Trabajar con autoridades y organismos públicos' },
        { id: '8', description: 'Promover cambio social y equidad' },
        { id: '9', description: 'Asistir a formaciones y capacitaciones' },
        { id: '10', description: 'Demostrar compromiso con poblaciones marginadas' },
      ],
    },
    {
      name: 'Idiomas',
      activities: [
        { id: '1', description: 'Enseñar gramatica y pronunciación' },
        { id: '2', description: 'Diseñar materiales didácticos para aprendizaje' },
        { id: '3', description: 'Evaluar nivel de comprensión de estudiantes' },
        { id: '4', description: 'Practicar conversación y expresión oral' },
        { id: '5', description: 'Traducir documentos y textos' },
        { id: '6', description: 'Investigar nueva metodologías de enseñanza' },
        { id: '7', description: 'Viajar a países donde se habla el idioma' },
        { id: '8', description: 'Mantenerse actualizado con cambios lingüísticos' },
        { id: '9', description: 'Evaluar exámenes y certificaciones' },
        { id: '10', description: 'Trabajar con estudiantes de diferentes edades' },
      ],
    },
    {
      name: 'Periodismo',
      activities: [
        { id: '1', description: 'Investigar y reportar historias de interés público' },
        { id: '2', description: 'Escribir artículos y notas periodísticas' },
        { id: '3', description: 'Conducir entrevistas a personajes relevantes' },
        { id: '4', description: 'Verificar información y datos antes de publicar' },
        { id: '5', description: 'Trabajar bajo presión de plazos ajustados' },
        { id: '6', description: 'Colaborar con editores y correctores' },
        { id: '7', description: 'Estar atento a noticias de último momento' },
        { id: '8', description: 'Usar herramientas de investigación digital' },
        { id: '9', description: 'Mantener ética profesional y objetividad' },
        { id: '10', description: 'Informar al público sobre asuntos relevantes' },
      ],
    },
    {
      name: 'Derecho',
      activities: [
        { id: '1', description: 'Asesorar a clientes sobre cuestiones legales' },
        { id: '2', description: 'Preparar documentos y contratos legales' },
        { id: '3', description: 'Representar clientes en procesos judiciales' },
        { id: '4', description: 'Investigar casos y recopilar evidencia' },
        { id: '5', description: 'Negociar acuerdos y soluciones' },
        { id: '6', description: 'Actualizarse sobre cambios en leyes y regulaciones' },
        { id: '7', description: 'Argumentar casos oralmente ante jueces' },
        { id: '8', description: 'Trabajar con documentación compleja' },
        { id: '9', description: 'Mantener confidencialidad profesional' },
        { id: '10', description: 'Defender derechos e intereses de clientes' },
      ],
    },
    {
      name: 'Historia y geografía',
      activities: [
        { id: '1', description: 'Enseñar eventos históricos y contexto global' },
        { id: '2', description: 'Investigar fuentes históricas y documentos' },
        { id: '3', description: 'Explicar fenómenos geográficos y climáticos' },
        { id: '4', description: 'Hacer análisis comparativos entre periodos' },
        { id: '5', description: 'Llevar a cabo excursiones educativas' },
        { id: '6', description: 'Usar mapas, gráficos y recursos visuales' },
        { id: '7', description: 'Preparar estudiantes para exámenes' },
        { id: '8', description: 'Conectar historia con eventos contemporáneos' },
        { id: '9', description: 'Fomentar pensamiento crítico' },
        { id: '10', description: 'Inspirar curiosidad sobre el mundo' },
      ],
    },
    {
      name: 'Educación infantil',
      activities: [
        { id: '1', description: 'Planificar actividades educativas para niños pequeños' },
        { id: '2', description: 'Enseñar valores, comportamiento y socialización' },
        { id: '3', description: 'Estimular desarrollo cognitivo y motriz' },
        { id: '4', description: 'Cambiar pañales, alimentar y cuidar' },
        { id: '5', description: 'Comunicarse con padres sobre progreso del niño' },
        { id: '6', description: 'Crear ambiente seguro y acogedor' },
        { id: '7', description: 'Usar juegos y actividades como herramientas' },
        { id: '8', description: 'Identificar problemas de desarrollo temprano' },
        { id: '9', description: 'Trabajar con paciencia y dedicación' },
        { id: '10', description: 'Contribuir a formación de nuevas generaciones' },
      ],
    },
    {
  name: 'Educación internacional',
  activities: [
    { id: '1', description: 'Diseñar y coordinar programas educativos con enfoque global' },
    { id: '2', description: 'Trabajar en instituciones educativas internacionales o bilingües' },
    { id: '3', description: 'Promover el intercambio cultural y académico entre países' },
    { id: '4', description: 'Asesorar sobre políticas y sistemas educativos en distintos contextos' },
    { id: '5', description: 'Gestionar becas, convenios y programas de movilidad estudiantil' },
    { id: '6', description: 'Desarrollar materiales didácticos interculturales' },
    { id: '7', description: 'Participar en proyectos de cooperación educativa internacional' },
    { id: '8', description: 'Investigar sobre educación comparada y globalización' },
    { id: '9', description: 'Capacitar docentes en prácticas pedagógicas interculturales' },
    { id: '10', description: 'Representar a instituciones en redes y organismos internacionales' },
  ],
},
{
  name: 'Periodismo digital',
  activities: [
    { id: '1', description: 'Investigar y redactar noticias para medios digitales' },
    { id: '2', description: 'Crear contenido multimedia para redes sociales y portales web' },
    { id: '3', description: 'Verificar fuentes y datos en tiempo real' },
    { id: '4', description: 'Usar herramientas de edición de video, audio e imagen' },
    { id: '5', description: 'Cubrir eventos en vivo y generar transmisiones online' },
    { id: '6', description: 'Analizar tendencias informativas y comportamiento de audiencia' },
    { id: '7', description: 'Gestionar y posicionar contenidos en plataformas digitales' },
    { id: '8', description: 'Trabajar con SEO y estrategias de comunicación digital' },
    { id: '9', description: 'Colaborar con equipos de redacción y diseño web' },
    { id: '10', description: 'Mantener una ética periodística en entornos digitales' },
  ],
},
{
  name: 'Ciencias políticas',
  activities: [
    { id: '1', description: 'Analizar sistemas políticos, instituciones y procesos de gobierno' },
    { id: '2', description: 'Investigar políticas públicas y su impacto social' },
    { id: '3', description: 'Asesorar a organismos públicos, partidos o ONGs' },
    { id: '4', description: 'Participar en campañas electorales y comunicación política' },
    { id: '5', description: 'Redactar informes, proyectos o propuestas de políticas públicas' },
    { id: '6', description: 'Investigar sobre relaciones internacionales y diplomacia' },
    { id: '7', description: 'Enseñar o divulgar temas políticos en medios y universidades' },
    { id: '8', description: 'Analizar datos y encuestas de opinión pública' },
    { id: '9', description: 'Promover la participación ciudadana y democrática' },
    { id: '10', description: 'Mantenerse actualizado en temas geopolíticos y sociales' },
  ],
},
{
  name: 'Sociología',
  activities: [
    { id: '1', description: 'Investigar el comportamiento y las estructuras sociales' },
    { id: '2', description: 'Diseñar encuestas, entrevistas y estudios de campo' },
    { id: '3', description: 'Analizar datos y elaborar informes sobre problemáticas sociales' },
    { id: '4', description: 'Trabajar en proyectos de desarrollo comunitario o urbano' },
    { id: '5', description: 'Colaborar con instituciones públicas o privadas en diagnósticos sociales' },
    { id: '6', description: 'Asesorar en políticas sociales, laborales o educativas' },
    { id: '7', description: 'Investigar temas como desigualdad, género, juventud o migraciones' },
    { id: '8', description: 'Divulgar resultados de investigación en medios o congresos' },
    { id: '9', description: 'Participar en equipos interdisciplinarios de análisis social' },
    { id: '10', description: 'Contribuir al diseño de estrategias para mejorar la convivencia social' },
  ],
},
{
  name: 'Antropología',
  activities: [
    { id: '1', description: 'Estudiar las culturas, costumbres y modos de vida de distintas comunidades' },
    { id: '2', description: 'Realizar trabajo de campo y observación participante' },
    { id: '3', description: 'Analizar objetos, relatos y manifestaciones culturales' },
    { id: '4', description: 'Investigar temas sobre identidad, religión o parentesco' },
    { id: '5', description: 'Colaborar con museos, universidades y organizaciones sociales' },
    { id: '6', description: 'Escribir informes y publicaciones científicas sobre culturas' },
    { id: '7', description: 'Asesorar proyectos de desarrollo respetando la diversidad cultural' },
    { id: '8', description: 'Comparar comportamientos sociales en distintos contextos' },
    { id: '9', description: 'Participar en la preservación del patrimonio cultural' },
    { id: '10', description: 'Promover la valoración del pluralismo y la interculturalidad' },
  ],
},
{
  name: 'Arqueología',
  activities: [
    { id: '1', description: 'Realizar excavaciones y estudios de sitios arqueológicos' },
    { id: '2', description: 'Analizar restos materiales como cerámica, herramientas o huesos' },
    { id: '3', description: 'Registrar y catalogar hallazgos de valor histórico o cultural' },
    { id: '4', description: 'Trabajar en museos, laboratorios o proyectos de campo' },
    { id: '5', description: 'Aplicar técnicas de datación y conservación de materiales antiguos' },
    { id: '6', description: 'Colaborar con historiadores, antropólogos y conservadores' },
    { id: '7', description: 'Elaborar informes científicos y publicaciones académicas' },
    { id: '8', description: 'Participar en la protección y difusión del patrimonio arqueológico' },
    { id: '9', description: 'Supervisar excavaciones y formación de equipos de campo' },
    { id: '10', description: 'Promover el respeto y la preservación de los sitios culturales' },
  ],
},
{
  name: 'Gestión social y desarrollo',
  activities: [
    { id: '1', description: 'Diseñar y coordinar proyectos sociales y comunitarios' },
    { id: '2', description: 'Trabajar con organizaciones gubernamentales y ONG' },
    { id: '3', description: 'Identificar problemáticas sociales y planificar soluciones participativas' },
    { id: '4', description: 'Gestionar recursos humanos y financieros en programas sociales' },
    { id: '5', description: 'Evaluar el impacto de políticas y acciones comunitarias' },
    { id: '6', description: 'Promover la inclusión, la equidad y el desarrollo sostenible' },
    { id: '7', description: 'Capacitar líderes y actores sociales locales' },
    { id: '8', description: 'Fomentar la participación ciudadana y el trabajo en red' },
    { id: '9', description: 'Supervisar equipos interdisciplinarios de intervención social' },
    { id: '10', description: 'Elaborar informes y estrategias para fortalecer el desarrollo comunitario' },
  ],
},
{
  name: 'Consejería familiar',
  activities: [
    { id: '1', description: 'Orientar a familias en la resolución de conflictos y dificultades' },
    { id: '2', description: 'Escuchar activamente y brindar apoyo emocional a los consultantes' },
    { id: '3', description: 'Guiar procesos de comunicación y vínculos familiares saludables' },
    { id: '4', description: 'Diseñar estrategias de acompañamiento y contención psicológica' },
    { id: '5', description: 'Trabajar en instituciones educativas, centros de salud o comunitarios' },
    { id: '6', description: 'Detectar problemáticas como violencia, adicciones o crisis vinculares' },
    { id: '7', description: 'Derivar a profesionales especializados cuando sea necesario' },
    { id: '8', description: 'Promover la educación afectiva y el respeto mutuo en el hogar' },
    { id: '9', description: 'Organizar talleres y charlas de orientación familiar' },
    { id: '10', description: 'Actualizarse en enfoques de mediación y acompañamiento terapéutico' },
  ],
},
{
  name: 'Comunicación y publicidad',
  activities: [
    { id: '1', description: 'Planificar y ejecutar campañas publicitarias creativas' },
    { id: '2', description: 'Desarrollar estrategias de comunicación para marcas o instituciones' },
    { id: '3', description: 'Redactar textos publicitarios y guiones para medios diversos' },
    { id: '4', description: 'Analizar públicos y posicionamiento de productos o servicios' },
    { id: '5', description: 'Supervisar la producción de piezas gráficas, radiales o audiovisuales' },
    { id: '6', description: 'Gestionar la presencia de marcas en redes sociales y plataformas digitales' },
    { id: '7', description: 'Coordinar equipos creativos y de diseño' },
    { id: '8', description: 'Evaluar la efectividad de campañas y estrategias de comunicación' },
    { id: '9', description: 'Colaborar con agencias, medios y departamentos de marketing' },
    { id: '10', description: 'Mantenerse actualizado en tendencias de consumo y medios digitales' },
  ],
},
{
  name: 'Administración educativa',
  activities: [
    { id: '1', description: 'Planificar y coordinar la gestión institucional de centros educativos' },
    { id: '2', description: 'Supervisar equipos docentes y administrativos' },
    { id: '3', description: 'Gestionar recursos humanos, materiales y financieros de la institución' },
    { id: '4', description: 'Diseñar proyectos educativos y planes de mejora institucional' },
    { id: '5', description: 'Evaluar el funcionamiento y la calidad educativa' },
    { id: '6', description: 'Promover la participación de la comunidad escolar' },
    { id: '7', description: 'Implementar políticas educativas y normativas vigentes' },
    { id: '8', description: 'Organizar jornadas, reuniones y actividades institucionales' },
    { id: '9', description: 'Gestionar la comunicación interna y externa del establecimiento' },
    { id: '10', description: 'Actualizarse en liderazgo pedagógico y gestión educativa moderna' },
  ],
},
{
  name: 'Educación especial',
  activities: [
    { id: '1', description: 'Acompañar a personas con discapacidades o dificultades de aprendizaje' },
    { id: '2', description: 'Diseñar estrategias pedagógicas adaptadas a cada necesidad' },
    { id: '3', description: 'Trabajar en equipos interdisciplinarios con otros profesionales' },
    { id: '4', description: 'Promover la inclusión y la autonomía de los estudiantes' },
    { id: '5', description: 'Evaluar y registrar avances en los procesos de aprendizaje' },
    { id: '6', description: 'Orientar a familias y docentes sobre prácticas inclusivas' },
    { id: '7', description: 'Utilizar recursos didácticos específicos y tecnologías adaptadas' },
    { id: '8', description: 'Intervenir en contextos educativos formales y no formales' },
    { id: '9', description: 'Participar en proyectos de integración escolar' },
    { id: '10', description: 'Actualizarse en neuroeducación y enfoques inclusivos' },
  ],
},
{
  name: 'Psicopedagogía',
  activities: [
    { id: '1', description: 'Evaluar y acompañar procesos de aprendizaje en niños, jóvenes o adultos' },
    { id: '2', description: 'Detectar dificultades cognitivas, emocionales o sociales que afectan el aprendizaje' },
    { id: '3', description: 'Diseñar estrategias personalizadas de intervención pedagógica' },
    { id: '4', description: 'Trabajar en escuelas, gabinetes psicopedagógicos o consultorios privados' },
    { id: '5', description: 'Colaborar con docentes y familias para mejorar el rendimiento escolar' },
    { id: '6', description: 'Realizar diagnósticos y evaluaciones psicopedagógicas' },
    { id: '7', description: 'Acompañar procesos de orientación vocacional y personal' },
    { id: '8', description: 'Participar en equipos de orientación escolar' },
    { id: '9', description: 'Desarrollar programas de estimulación cognitiva' },
    { id: '10', description: 'Formarse continuamente en psicología, educación y neurociencias' },
  ],
},
{
  name: 'Estimulación temprana',
  activities: [
    { id: '1', description: 'Favorecer el desarrollo integral de bebés y niños pequeños' },
    { id: '2', description: 'Detectar señales tempranas de dificultades en el desarrollo' },
    { id: '3', description: 'Diseñar actividades lúdicas para estimular el lenguaje, la motricidad y la cognición' },
    { id: '4', description: 'Trabajar junto a familias y profesionales de la salud' },
    { id: '5', description: 'Acompañar procesos de desarrollo emocional y social' },
    { id: '6', description: 'Crear entornos seguros y estimulantes para el aprendizaje temprano' },
    { id: '7', description: 'Evaluar avances y registrar progresos en cada etapa' },
    { id: '8', description: 'Participar en equipos interdisciplinarios de atención infantil' },
    { id: '9', description: 'Brindar orientación a padres sobre crianza y estimulación adecuada' },
    { id: '10', description: 'Actualizarse en neurodesarrollo y psicomotricidad infantil' },
  ],
},
{
  name: 'Traducción simultánea',
  activities: [
    { id: '1', description: 'Interpretar discursos y conferencias en tiempo real' },
    { id: '2', description: 'Traducir de manera oral o escrita textos especializados' },
    { id: '3', description: 'Dominar varios idiomas y sus matices culturales' },
    { id: '4', description: 'Trabajar en congresos, organismos internacionales o medios de comunicación' },
    { id: '5', description: 'Preparar glosarios y materiales previos a los eventos' },
    { id: '6', description: 'Usar cabinas, micrófonos y equipos de interpretación profesional' },
    { id: '7', description: 'Adaptar el mensaje sin alterar su sentido original' },
    { id: '8', description: 'Mantener la concentración y rapidez en entornos exigentes' },
    { id: '9', description: 'Colaborar con traductores, técnicos y organizadores de eventos' },
    { id: '10', description: 'Actualizarse en terminología y tecnologías de traducción' },
  ],
},
{
  name: 'Lingüística',
  activities: [
    { id: '1', description: 'Analizar la estructura y evolución de los idiomas' },
    { id: '2', description: 'Investigar los sonidos, significados y gramática de las lenguas' },
    { id: '3', description: 'Estudiar la relación entre lenguaje, cultura y pensamiento' },
    { id: '4', description: 'Aplicar teorías lingüísticas a la enseñanza de idiomas' },
    { id: '5', description: 'Trabajar en la creación de diccionarios y corpus lingüísticos' },
    { id: '6', description: 'Asesorar en traducción y localización de textos' },
    { id: '7', description: 'Investigar lenguas originarias y en peligro de extinción' },
    { id: '8', description: 'Colaborar en proyectos de inteligencia artificial y procesamiento del lenguaje natural' },
    { id: '9', description: 'Publicar artículos y materiales académicos sobre lingüística' },
    { id: '10', description: 'Participar en congresos y redes de investigación lingüística' },
  ],
},
{
  name: 'Bibliotecología',
  activities: [
    { id: '1', description: 'Organizar y catalogar materiales bibliográficos y digitales' },
    { id: '2', description: 'Atender al público y orientar en la búsqueda de información' },
    { id: '3', description: 'Gestionar préstamos y devoluciones de materiales' },
    { id: '4', description: 'Diseñar sistemas de clasificación y bases de datos bibliográficas' },
    { id: '5', description: 'Conservar y restaurar documentos y archivos antiguos' },
    { id: '6', description: 'Implementar tecnologías de la información en bibliotecas' },
    { id: '7', description: 'Coordinar programas culturales y de fomento a la lectura' },
    { id: '8', description: 'Evaluar y actualizar colecciones bibliográficas' },
    { id: '9', description: 'Capacitar a usuarios en alfabetización informacional' },
    { id: '10', description: 'Colaborar con redes de bibliotecas y centros de documentación' },
  ],
},
{
  name: 'Museología',
  activities: [
    { id: '1', description: 'Planificar y organizar exposiciones y muestras culturales' },
    { id: '2', description: 'Catalogar y conservar piezas de valor histórico o artístico' },
    { id: '3', description: 'Diseñar estrategias educativas para visitantes' },
    { id: '4', description: 'Coordinar préstamos y traslados de obras entre museos' },
    { id: '5', description: 'Investigar el contexto histórico de las colecciones' },
    { id: '6', description: 'Gestionar presupuestos y recursos de museos' },
    { id: '7', description: 'Aplicar técnicas de conservación preventiva' },
    { id: '8', description: 'Colaborar con restauradores y curadores de arte' },
    { id: '9', description: 'Elaborar catálogos y materiales informativos de exhibiciones' },
    { id: '10', description: 'Promover la accesibilidad cultural en espacios museísticos' },
  ],
},
{
  name: 'Relaciones internacionales y diplomacia',
  activities: [
    { id: '1', description: 'Analizar y negociar acuerdos entre países e instituciones' },
    { id: '2', description: 'Representar intereses nacionales en organismos internacionales' },
    { id: '3', description: 'Asesorar en políticas exteriores y cooperación internacional' },
    { id: '4', description: 'Participar en misiones diplomáticas y embajadas' },
    { id: '5', description: 'Redactar informes y comunicados sobre temas internacionales' },
    { id: '6', description: 'Organizar cumbres, conferencias y reuniones bilaterales' },
    { id: '7', description: 'Promover relaciones comerciales y culturales entre países' },
    { id: '8', description: 'Analizar contextos geopolíticos y de derechos humanos' },
    { id: '9', description: 'Mediar en conflictos y negociaciones internacionales' },
    { id: '10', description: 'Representar instituciones en foros y organismos multilaterales' },
  ],
},
{
  name: 'Comunicación social con énfasis en márquetin y gestión de empresas',
  activities: [
    { id: '1', description: 'Diseñar estrategias de comunicación y marketing empresarial' },
    { id: '2', description: 'Coordinar campañas publicitarias y promocionales' },
    { id: '3', description: 'Analizar el posicionamiento de marcas y públicos objetivos' },
    { id: '4', description: 'Crear contenido para redes sociales y medios digitales' },
    { id: '5', description: 'Supervisar la imagen institucional y comunicación interna' },
    { id: '6', description: 'Organizar eventos corporativos y ruedas de prensa' },
    { id: '7', description: 'Elaborar informes de impacto y métricas de comunicación' },
    { id: '8', description: 'Gestionar relaciones con medios de comunicación' },
    { id: '9', description: 'Asesorar a empresas en responsabilidad social y branding' },
    { id: '10', description: 'Capacitar en liderazgo y comunicación efectiva' },
  ],
},
{
  name: 'Redacción creativa y publicitaria',
  activities: [
    { id: '1', description: 'Escribir textos persuasivos para campañas publicitarias' },
    { id: '2', description: 'Crear guiones para radio, televisión o redes sociales' },
    { id: '3', description: 'Diseñar slogans y mensajes atractivos para marcas' },
    { id: '4', description: 'Colaborar con diseñadores y directores de arte en campañas' },
    { id: '5', description: 'Adaptar textos según el público y el medio de difusión' },
    { id: '6', description: 'Revisar y editar materiales publicitarios y corporativos' },
    { id: '7', description: 'Proponer ideas creativas para lanzamientos de productos' },
    { id: '8', description: 'Elaborar storytelling y narrativas de marca' },
    { id: '9', description: 'Investigar tendencias de consumo y lenguaje publicitario' },
    { id: '10', description: 'Trabajar en agencias de publicidad o medios digitales' },
  ],
},
{
  name: 'Relaciones públicas y comunicación organizacional',
  activities: [
    { id: '1', description: 'Diseñar planes de comunicación institucional' },
    { id: '2', description: 'Mantener relaciones positivas con medios y stakeholders' },
    { id: '3', description: 'Gestionar crisis de reputación y comunicación de emergencia' },
    { id: '4', description: 'Organizar eventos corporativos y conferencias de prensa' },
    { id: '5', description: 'Coordinar la comunicación interna de la organización' },
    { id: '6', description: 'Supervisar la imagen y cultura corporativa' },
    { id: '7', description: 'Elaborar boletines, discursos y comunicados oficiales' },
    { id: '8', description: 'Asesorar a directivos en relaciones públicas y protocolo' },
    { id: '9', description: 'Monitorear la percepción pública de la marca' },
    { id: '10', description: 'Fomentar la responsabilidad social empresarial' },
  ],
},
{
  name: 'Hotelería y turismo',
  activities: [
    { id: '1', description: 'Coordinar reservas y atención a huéspedes' },
    { id: '2', description: 'Planificar itinerarios y experiencias turísticas' },
    { id: '3', description: 'Organizar eventos y congresos en hoteles' },
    { id: '4', description: 'Gestionar la operación de establecimientos hoteleros' },
    { id: '5', description: 'Promocionar destinos turísticos y culturales' },
    { id: '6', description: 'Supervisar personal de recepción, limpieza y catering' },
    { id: '7', description: 'Diseñar estrategias de servicio al cliente' },
    { id: '8', description: 'Garantizar el cumplimiento de normas sanitarias y de calidad' },
    { id: '9', description: 'Desarrollar alianzas con agencias de viajes y operadores' },
    { id: '10', description: 'Fomentar el turismo sustentable y responsable' },
  ],
},
{
  name: 'Teología',
  activities: [
    { id: '1', description: 'Estudiar las doctrinas, textos sagrados y tradiciones religiosas' },
    { id: '2', description: 'Analizar la relación entre fe, ética y sociedad' },
    { id: '3', description: 'Impartir clases y conferencias sobre religión y filosofía' },
    { id: '4', description: 'Asesorar a comunidades en temas de espiritualidad' },
    { id: '5', description: 'Investigar el impacto social de las religiones' },
    { id: '6', description: 'Participar en proyectos de diálogo interreligioso' },
    { id: '7', description: 'Redactar ensayos, artículos o libros teológicos' },
    { id: '8', description: 'Colaborar en instituciones educativas o eclesiásticas' },
    { id: '9', description: 'Guiar reflexiones éticas en contextos sociales diversos' },
    { id: '10', description: 'Acompañar procesos de orientación vocacional religiosa' },
  ],
},
{
  name: 'Institución sacerdotal',
  activities: [
    { id: '1', description: 'Celebrar ceremonias religiosas y sacramentos' },
    { id: '2', description: 'Acompañar espiritualmente a personas y comunidades' },
    { id: '3', description: 'Predicar y orientar sobre principios de fe y valores' },
    { id: '4', description: 'Organizar actividades pastorales y comunitarias' },
    { id: '5', description: 'Colaborar con instituciones sociales y de caridad' },
    { id: '6', description: 'Promover el diálogo y la paz en contextos sociales' },
    { id: '7', description: 'Gestionar recursos y mantenimiento de templos o parroquias' },
    { id: '8', description: 'Brindar asistencia espiritual en hospitales o cárceles' },
    { id: '9', description: 'Formar a nuevos miembros del clero o líderes laicos' },
    { id: '10', description: 'Participar en encuentros y misiones religiosas' },
  ],
},

  ],
  'III': [
    {
      name: 'Administración de empresas',
      activities: [
        { id: '1', description: 'Planificar estrategia y objetivos empresariales' },
        { id: '2', description: 'Gestionar recursos humanos y financieros' },
        { id: '3', description: 'Tomar decisiones basadas en datos y análisis' },
        { id: '4', description: 'Supervisar operaciones diarias de la empresa' },
        { id: '5', description: 'Coordinarse con departamentos diversos' },
        { id: '6', description: 'Resolver problemas y conflictos empresariales' },
        { id: '7', description: 'Preparar reportes de desempeño' },
        { id: '8', description: 'Negociar con proveedores y socios' },
        { id: '9', description: 'Implementar mejoras en procesos' },
        { id: '10', description: 'Liderar equipos hacia cumplimiento de metas' },
      ],
    },
    {
      name: 'Contabilidad',
      activities: [
        { id: '1', description: 'Registrar transacciones financieras' },
        { id: '2', description: 'Conciliar cuentas bancarias y registros' },
        { id: '3', description: 'Preparar balances y estados financieros' },
        { id: '4', description: 'Calcular impuestos y obligaciones tributarias' },
        { id: '5', description: 'Usar software contable especializado' },
        { id: '6', description: 'Auditar registros financieros' },
        { id: '7', description: 'Identificar discrepancias y errores' },
        { id: '8', description: 'Asesorar sobre decisiones financieras' },
        { id: '9', description: 'Mantener archivo de documentos organizados' },
        { id: '10', description: 'Cumplir con regulaciones y normas contables' },
      ],
    },
    {
      name: 'Ventas',
      activities: [
        { id: '1', description: 'Contactar y prospectar clientes potenciales' },
        { id: '2', description: 'Presentar productos/servicios de manera convincente' },
        { id: '3', description: 'Negociar precios y términos de venta' },
        { id: '4', description: 'Cerrar transacciones y contratos' },
        { id: '5', description: 'Hacer seguimiento post-venta' },
        { id: '6', description: 'Trabajar con objetivos y cuotas de venta' },
        { id: '7', description: 'Usar herramientas CRM y sistemas' },
        { id: '8', description: 'Resolver objeciones de clientes' },
        { id: '9', description: 'Generar reportes de actividad' },
        { id: '10', description: 'Construir relaciones a largo plazo con clientes' },
      ],
    },
    {
      name: 'Márquetin estratégico',
      activities: [
        { id: '1', description: 'Investigar mercado y competencia' },
        { id: '2', description: 'Diseñar estrategias de marketing' },
        { id: '3', description: 'Analizar datos de campaña y resultados' },
        { id: '4', description: 'Crear contenido promocional atractivo' },
        { id: '5', description: 'Gestionar presupuestos de marketing' },
        { id: '6', description: 'Coordinar campañas en múltiples canales' },
        { id: '7', description: 'Trabajar con agencias creativas' },
        { id: '8', description: 'Monitorear redes sociales y métricas' },
        { id: '9', description: 'Presentar resultados a directivos' },
        { id: '10', description: 'Innovar en estrategias de promoción' },
      ],
    },
    {
      name: 'Recursos Humanos',
      activities: [
        { id: '1', description: 'Reclutar y seleccionar nuevos empleados' },
        { id: '2', description: 'Conducir entrevistas a candidatos' },
        { id: '3', description: 'Diseñar programas de capacitación' },
        { id: '4', description: 'Evaluar desempeño de empleados' },
        { id: '5', description: 'Resolver conflictos laborales' },
        { id: '6', description: 'Administrar nómina y beneficios' },
        { id: '7', description: 'Mantener expedientes de personal' },
        { id: '8', description: 'Asegurar cumplimiento de leyes laborales' },
        { id: '9', description: 'Promover cultura organizacional' },
        { id: '10', description: 'Desarrollar planes de carrera para empleados' },
      ],
    },
    {
      name: 'Emprendimiento',
      activities: [
        { id: '1', description: 'Identificar oportunidades de negocio' },
        { id: '2', description: 'Crear planes de negocio detallados' },
        { id: '3', description: 'Buscar financiamiento e inversores' },
        { id: '4', description: 'Poner en marcha una nueva empresa' },
        { id: '5', description: 'Trabajar bajo incertidumbre' },
        { id: '6', description: 'Usar creatividad para resolver problemas' },
        { id: '7', description: 'Liderar equipo pequeño' },
        { id: '8', description: 'Asumir riesgos calculados' },
        { id: '9', description: 'Buscar asesoría de mentores' },
        { id: '10', description: 'Adaptarse rápidamente a cambios' },
      ],
    },
    {
  name: 'Auditoría',
  activities: [
    { id: '1', description: 'Revisar y analizar estados financieros de empresas' },
    { id: '2', description: 'Evaluar el cumplimiento de normas contables y fiscales' },
    { id: '3', description: 'Detectar errores, fraudes o irregularidades contables' },
    { id: '4', description: 'Elaborar informes y recomendaciones de mejora financiera' },
    { id: '5', description: 'Supervisar la correcta aplicación de políticas internas' },
    { id: '6', description: 'Asesorar en control de riesgos y gestión interna' },
    { id: '7', description: 'Participar en auditorías externas e internas' },
    { id: '8', description: 'Evaluar la eficiencia de procesos administrativos' },
    { id: '9', description: 'Colaborar con organismos de control y fiscalización' },
    { id: '10', description: 'Mantenerse actualizado en normas contables y legales' },
  ],
},
{
  name: 'Gestión y negocios internacionales',
  activities: [
    { id: '1', description: 'Analizar mercados internacionales y oportunidades de expansión' },
    { id: '2', description: 'Negociar acuerdos comerciales entre países o empresas' },
    { id: '3', description: 'Coordinar importaciones, exportaciones y logística global' },
    { id: '4', description: 'Desarrollar estrategias de internacionalización empresarial' },
    { id: '5', description: 'Gestionar relaciones con clientes y socios extranjeros' },
    { id: '6', description: 'Analizar políticas económicas y comerciales internacionales' },
    { id: '7', description: 'Supervisar operaciones financieras en moneda extranjera' },
    { id: '8', description: 'Organizar ferias, misiones comerciales y eventos empresariales' },
    { id: '9', description: 'Asesorar en temas de cultura corporativa y negociación intercultural' },
    { id: '10', description: 'Promover inversiones y cooperación internacional' },
  ],
},
{
  name: 'Gestión empresarial',
  activities: [
    { id: '1', description: 'Planificar estrategias para el crecimiento organizacional' },
    { id: '2', description: 'Supervisar el funcionamiento de diferentes áreas de la empresa' },
    { id: '3', description: 'Analizar indicadores de productividad y eficiencia' },
    { id: '4', description: 'Coordinar equipos de trabajo y liderazgo organizacional' },
    { id: '5', description: 'Evaluar presupuestos, costos y beneficios' },
    { id: '6', description: 'Definir políticas de recursos humanos y comunicación interna' },
    { id: '7', description: 'Aplicar herramientas de gestión de calidad y mejora continua' },
    { id: '8', description: 'Gestionar proyectos de innovación y sostenibilidad' },
    { id: '9', description: 'Diseñar planes de marketing y expansión comercial' },
    { id: '10', description: 'Adaptar la empresa a cambios del entorno económico' },
  ],
},
{
  name: 'Gestión financiera',
  activities: [
    { id: '1', description: 'Administrar presupuestos, ingresos y egresos de una organización' },
    { id: '2', description: 'Elaborar reportes financieros y de rentabilidad' },
    { id: '3', description: 'Analizar inversiones y fuentes de financiamiento' },
    { id: '4', description: 'Evaluar riesgos financieros y proponer estrategias de mitigación' },
    { id: '5', description: 'Gestionar la liquidez y flujo de caja de la empresa' },
    { id: '6', description: 'Supervisar la contabilidad general y fiscal' },
    { id: '7', description: 'Optimizar el uso de recursos financieros disponibles' },
    { id: '8', description: 'Asesorar en decisiones de inversión y ahorro' },
    { id: '9', description: 'Controlar costos y analizar márgenes de ganancia' },
    { id: '10', description: 'Aplicar herramientas tecnológicas para el análisis financiero' },
  ],
},
{
  name: 'Ingeniería comercial',
  activities: [
    { id: '1', description: 'Analizar mercados y comportamiento del consumidor' },
    { id: '2', description: 'Desarrollar estrategias de marketing y ventas' },
    { id: '3', description: 'Aplicar modelos económicos a la toma de decisiones empresariales' },
    { id: '4', description: 'Evaluar proyectos de inversión y rentabilidad' },
    { id: '5', description: 'Diseñar planes comerciales y de posicionamiento de marca' },
    { id: '6', description: 'Optimizar procesos productivos y logísticos' },
    { id: '7', description: 'Supervisar presupuestos y planificación estratégica' },
    { id: '8', description: 'Implementar herramientas de análisis financiero y estadístico' },
    { id: '9', description: 'Gestionar relaciones con clientes y socios comerciales' },
    { id: '10', description: 'Promover la innovación y competitividad empresarial' },
  ],
},
{
  name: 'Comercio exterior',
  activities: [
    { id: '1', description: 'Coordinar operaciones de exportación e importación de productos' },
    { id: '2', description: 'Gestionar documentos aduaneros y logísticos' },
    { id: '3', description: 'Negociar contratos y acuerdos comerciales internacionales' },
    { id: '4', description: 'Analizar mercados externos y oportunidades de negocio' },
    { id: '5', description: 'Supervisar el cumplimiento de normativas aduaneras' },
    { id: '6', description: 'Controlar costos y tiempos en procesos logísticos' },
    { id: '7', description: 'Coordinar con agentes de transporte, seguros y aduanas' },
    { id: '8', description: 'Diseñar estrategias de internacionalización empresarial' },
    { id: '9', description: 'Evaluar riesgos de tipo de cambio y comercio global' },
    { id: '10', description: 'Representar a empresas en ferias y misiones comerciales' },
  ],
},
{
  name: 'Banca y finanzas',
  activities: [
    { id: '1', description: 'Atender y asesorar a clientes sobre productos financieros' },
    { id: '2', description: 'Analizar solicitudes de crédito y capacidad de pago' },
    { id: '3', description: 'Supervisar operaciones bancarias y movimientos contables' },
    { id: '4', description: 'Evaluar inversiones y portafolios financieros' },
    { id: '5', description: 'Aplicar políticas de control y gestión de riesgos bancarios' },
    { id: '6', description: 'Desarrollar productos financieros y de ahorro' },
    { id: '7', description: 'Monitorear indicadores económicos y del mercado bursátil' },
    { id: '8', description: 'Cumplir con normativas financieras y regulatorias' },
    { id: '9', description: 'Atender operaciones de cambio, transferencias y préstamos' },
    { id: '10', description: 'Asesorar a empresas e individuos en planeación financiera' },
  ],
},
{
  name: 'Comunicaciones integradas en márquetin',
  activities: [
    { id: '1', description: 'Diseñar estrategias de comunicación coherentes entre diferentes medios' },
    { id: '2', description: 'Coordinar campañas publicitarias multicanal (radio, TV, redes, web)' },
    { id: '3', description: 'Analizar el posicionamiento de marca y comportamiento del consumidor' },
    { id: '4', description: 'Gestionar la identidad corporativa y la reputación de marca' },
    { id: '5', description: 'Supervisar la producción de contenidos promocionales' },
    { id: '6', description: 'Evaluar el impacto y retorno de inversión de campañas' },
    { id: '7', description: 'Colaborar con equipos creativos, de ventas y relaciones públicas' },
    { id: '8', description: 'Implementar estrategias digitales y de marketing de contenidos' },
    { id: '9', description: 'Monitorear tendencias de comunicación y consumo digital' },
    { id: '10', description: 'Asegurar la coherencia entre mensaje, público y canal' },
  ],
},
{
  name: 'Administración de empresas ecoturísticas y de hospitalidad',
  activities: [
    { id: '1', description: 'Planificar y gestionar servicios turísticos sostenibles' },
    { id: '2', description: 'Supervisar operaciones hoteleras y de alojamiento ecológico' },
    { id: '3', description: 'Desarrollar proyectos turísticos con enfoque ambiental' },
    { id: '4', description: 'Coordinar experiencias culturales, gastronómicas y naturales' },
    { id: '5', description: 'Capacitar al personal en atención al cliente y sostenibilidad' },
    { id: '6', description: 'Gestionar presupuestos y recursos para empresas turísticas' },
    { id: '7', description: 'Promocionar destinos ecoturísticos y actividades sustentables' },
    { id: '8', description: 'Supervisar el cumplimiento de normas ambientales y de calidad' },
    { id: '9', description: 'Establecer alianzas con comunidades locales y operadores' },
    { id: '10', description: 'Implementar políticas de turismo responsable y ético' },
  ],
},
{
  name: 'Ciencias económicas y financieras',
  activities: [
    { id: '1', description: 'Analizar variables económicas nacionales e internacionales' },
    { id: '2', description: 'Evaluar políticas fiscales, monetarias y de desarrollo' },
    { id: '3', description: 'Elaborar estudios sobre inflación, inversión y crecimiento económico' },
    { id: '4', description: 'Asesorar a empresas o gobiernos en estrategias económicas' },
    { id: '5', description: 'Modelar escenarios financieros para la toma de decisiones' },
    { id: '6', description: 'Realizar investigaciones sobre mercados y tendencias financieras' },
    { id: '7', description: 'Gestionar portafolios de inversión y riesgo' },
    { id: '8', description: 'Colaborar con instituciones bancarias o bursátiles' },
    { id: '9', description: 'Participar en proyectos de desarrollo económico y social' },
    { id: '10', description: 'Publicar informes y análisis económicos especializados' },
  ],
},
{
  name: 'Administración y ciencias políticas',
  activities: [
    { id: '1', description: 'Analizar políticas públicas y su impacto social y económico' },
    { id: '2', description: 'Diseñar estrategias de gestión en instituciones públicas o privadas' },
    { id: '3', description: 'Asesorar a gobiernos y organizaciones en planificación y liderazgo' },
    { id: '4', description: 'Supervisar la implementación de programas sociales y administrativos' },
    { id: '5', description: 'Elaborar diagnósticos y propuestas de políticas públicas' },
    { id: '6', description: 'Investigar sistemas políticos, electorales y de participación ciudadana' },
    { id: '7', description: 'Coordinar equipos de trabajo interdisciplinarios' },
    { id: '8', description: 'Promover la transparencia y la ética institucional' },
    { id: '9', description: 'Representar organismos en reuniones o foros políticos' },
    { id: '10', description: 'Evaluar resultados de gestión y formulación de políticas' },
  ],
},
{
  name: 'Ciencias empresariales',
  activities: [
    { id: '1', description: 'Planificar estrategias para el crecimiento y la rentabilidad empresarial' },
    { id: '2', description: 'Analizar mercados, competencia y oportunidades de negocio' },
    { id: '3', description: 'Diseñar políticas de recursos humanos, marketing y finanzas' },
    { id: '4', description: 'Supervisar operaciones administrativas y productivas' },
    { id: '5', description: 'Elaborar presupuestos y evaluar proyectos de inversión' },
    { id: '6', description: 'Fomentar la innovación y la responsabilidad social empresarial' },
    { id: '7', description: 'Dirigir equipos de trabajo y procesos de toma de decisiones' },
    { id: '8', description: 'Aplicar herramientas tecnológicas en la gestión empresarial' },
    { id: '9', description: 'Asesorar empresas en planificación estratégica y organización' },
    { id: '10', description: 'Monitorear indicadores económicos y de desempeño empresarial' },
  ],
},
{
  name: 'Comercio electrónico',
  activities: [
    { id: '1', description: 'Diseñar y gestionar tiendas online y plataformas de venta digital' },
    { id: '2', description: 'Optimizar la experiencia del usuario en entornos digitales' },
    { id: '3', description: 'Implementar estrategias de marketing digital y posicionamiento SEO/SEM' },
    { id: '4', description: 'Gestionar inventarios, envíos y atención al cliente online' },
    { id: '5', description: 'Analizar métricas de tráfico y conversión de ventas' },
    { id: '6', description: 'Coordinar campañas publicitarias y promociones online' },
    { id: '7', description: 'Proteger datos y transacciones con medidas de ciberseguridad' },
    { id: '8', description: 'Negociar con proveedores y plataformas de pago electrónico' },
    { id: '9', description: 'Actualizar catálogos y estrategias de precios dinámicos' },
    { id: '10', description: 'Innovar en estrategias omnicanal y fidelización de clientes' },
  ],
},
{
  name: 'Gestión de organismos públicos (municipios, ministerios, etc.)',
  activities: [
    { id: '1', description: 'Coordinar proyectos y programas de desarrollo local o nacional' },
    { id: '2', description: 'Administrar presupuestos y recursos públicos' },
    { id: '3', description: 'Supervisar procesos de contratación y compras estatales' },
    { id: '4', description: 'Evaluar el impacto social de las políticas públicas implementadas' },
    { id: '5', description: 'Promover la participación ciudadana y la transparencia institucional' },
    { id: '6', description: 'Elaborar informes técnicos y de rendición de cuentas' },
    { id: '7', description: 'Gestionar equipos de trabajo en entornos gubernamentales' },
    { id: '8', description: 'Coordinar relaciones entre organismos públicos y privados' },
    { id: '9', description: 'Diseñar estrategias de comunicación institucional y gobernanza' },
    { id: '10', description: 'Fomentar la eficiencia y la innovación en la gestión pública' },
  ],
},
{
  name: 'Gestión de centros educativos',
  activities: [
    { id: '1', description: 'Planificar y supervisar la administración de instituciones educativas' },
    { id: '2', description: 'Coordinar el personal docente y no docente del establecimiento' },
    { id: '3', description: 'Gestionar presupuestos, recursos y materiales escolares' },
    { id: '4', description: 'Evaluar la calidad educativa y el desempeño institucional' },
    { id: '5', description: 'Diseñar estrategias de mejora pedagógica y organizacional' },
    { id: '6', description: 'Promover la participación de familias y comunidad educativa' },
    { id: '7', description: 'Implementar políticas inclusivas y de convivencia escolar' },
    { id: '8', description: 'Asegurar el cumplimiento de normas legales y administrativas' },
    { id: '9', description: 'Fomentar la innovación educativa y el uso de nuevas tecnologías' },
    { id: '10', description: 'Representar al centro educativo ante autoridades y redes escolares' },
  ],
},

  ],
  'IV': [
    {
      name: 'Ingeniería en sistemas computacionales',
      activities: [
        { id: '1', description: 'Programar software y aplicaciones' },
        { id: '2', description: 'Diseñar arquitectura de sistemas' },
        { id: '3', description: 'Resolver problemas técnicos complejos' },
        { id: '4', description: 'Hacer pruebas y debugging de código' },
        { id: '5', description: 'Documentar especificaciones técnicas' },
        { id: '6', description: 'Colaborar en equipos de desarrollo' },
        { id: '7', description: 'Mantener y actualizar sistemas' },
        { id: '8', description: 'Investigar nuevas tecnologías' },
        { id: '9', description: 'Hacer revisiones de código' },
        { id: '10', description: 'Optimizar rendimiento de aplicaciones' },
      ],
    },
    {
      name: 'Ingeniería civil',
      activities: [
        { id: '1', description: 'Diseñar estructuras y edificios' },
        { id: '2', description: 'Calcular cargas y resistencia de materiales' },
        { id: '3', description: 'Hacer planos y especificaciones técnicas' },
        { id: '4', description: 'Supervisar obras de construcción' },
        { id: '5', description: 'Inspeccionar calidad de trabajos' },
        { id: '6', description: 'Presupuestar proyectos' },
        { id: '7', description: 'Coordinar con contratistas' },
        { id: '8', description: 'Asegurar cumplimiento de normativas' },
        { id: '9', description: 'Usar software CAD' },
        { id: '10', description: 'Resolver problemas constructivos' },
      ],
    },
    {
      name: 'Arquitectura',
      activities: [
        { id: '1', description: 'Diseñar conceptos arquitectónicos' },
        { id: '2', description: 'Crear planos y visualizaciones 3D' },
        { id: '3', description: 'Presentar propuestas a clientes' },
        { id: '4', description: 'Asegurar funcionalidad y estética' },
        { id: '5', description: 'Considerar sostenibilidad ambiental' },
        { id: '6', description: 'Coordinar con ingenieros' },
        { id: '7', description: 'Supervisar construcción' },
        { id: '8', description: 'Gestionar presupuestos' },
        { id: '9', description: 'Investigar materiales y técnicas' },
        { id: '10', description: 'Crear espacios inspiradores' },
      ],
    },
    {
      name: 'Electrónica',
      activities: [
        { id: '1', description: 'Diseñar circuitos electrónicos' },
        { id: '2', description: 'Soldar componentes' },
        { id: '3', description: 'Hacer pruebas de funcionamiento' },
        { id: '4', description: 'Reparar equipos electrónicos' },
        { id: '5', description: 'Usar osciloscopios y multímetros' },
        { id: '6', description: 'Leer esquemas eléctricos' },
        { id: '7', description: 'Investigar nuevas aplicaciones' },
        { id: '8', description: 'Documentar procesos técnicos' },
        { id: '9', description: 'Trabajar en laboratorio' },
        { id: '10', description: 'Resolver problemas de compatibilidad' },
      ],
    },
    {
      name: 'Telecomunicaciones',
      activities: [
        { id: '1', description: 'Diseñar redes de comunicación' },
        { id: '2', description: 'Instalar infraestructura de telecomunicaciones' },
        { id: '3', description: 'Mantener y actualizar sistemas' },
        { id: '4', description: 'Resolver problemas de conectividad' },
        { id: '5', description: 'Monitorear rendimiento de redes' },
        { id: '6', description: 'Configurar equipos de telecomunicaciones' },
        { id: '7', description: 'Investigar tecnologías emergentes' },
        { id: '8', description: 'Documentar cambios de infraestructura' },
        { id: '9', description: 'Colaborar con otros técnicos' },
        { id: '10', description: 'Asegurar calidad de servicio' },
      ],
    },
    {
      name: 'Ingeniería mecánica',
      activities: [
        { id: '1', description: 'Diseñar máquinas y componentes' },
        { id: '2', description: 'Realizar cálculos de ingeniería' },
        { id: '3', description: 'Hacer prototipos y modelos' },
        { id: '4', description: 'Usar software CAD y simulación' },
        { id: '5', description: 'Supervisar manufactura' },
        { id: '6', description: 'Hacer control de calidad' },
        { id: '7', description: 'Investigar materiales' },
        { id: '8', description: 'Resolver problemas técnicos' },
        { id: '9', description: 'Documentar diseños' },
        { id: '10', description: 'Innovar en procesos' },
      ],
    },
    {
  name: 'Geología',
  activities: [
    { id: '1', description: 'Estudiar la composición, estructura y procesos de la Tierra' },
    { id: '2', description: 'Analizar muestras de rocas, minerales y suelos' },
    { id: '3', description: 'Realizar exploraciones geológicas en campo' },
    { id: '4', description: 'Identificar recursos naturales como petróleo o minerales' },
    { id: '5', description: 'Investigar riesgos geológicos como terremotos o erupciones' },
    { id: '6', description: 'Usar software de modelado geológico y cartografía' },
    { id: '7', description: 'Colaborar con ingenieros en proyectos de construcción o minería' },
    { id: '8', description: 'Realizar estudios de impacto ambiental' },
    { id: '9', description: 'Trabajar en laboratorios o centros de investigación geológica' },
    { id: '10', description: 'Asesorar a empresas en exploración de recursos naturales' },
  ],
},
{
  name: 'Telemática',
  activities: [
    { id: '1', description: 'Diseñar e implementar redes de comunicación de datos' },
    { id: '2', description: 'Integrar sistemas informáticos con telecomunicaciones' },
    { id: '3', description: 'Administrar servidores y redes seguras' },
    { id: '4', description: 'Desarrollar soluciones de IoT (Internet de las cosas)' },
    { id: '5', description: 'Supervisar el tráfico y rendimiento de redes' },
    { id: '6', description: 'Investigar nuevas tecnologías de comunicación' },
    { id: '7', description: 'Realizar mantenimiento y soporte técnico de sistemas telemáticos' },
    { id: '8', description: 'Trabajar en proyectos de automatización y conectividad' },
    { id: '9', description: 'Optimizar la transmisión de datos en grandes redes' },
    { id: '10', description: 'Diseñar infraestructuras para redes inteligentes' },
  ],
},
{
  name: 'Ingeniería mecatrónica (robótica)',
  activities: [
    { id: '1', description: 'Diseñar y construir sistemas automatizados y robots' },
    { id: '2', description: 'Integrar mecánica, electrónica e informática en proyectos' },
    { id: '3', description: 'Programar controladores y sensores' },
    { id: '4', description: 'Diseñar prototipos de maquinaria inteligente' },
    { id: '5', description: 'Desarrollar soluciones de automatización industrial' },
    { id: '6', description: 'Simular y probar sistemas robóticos' },
    { id: '7', description: 'Trabajar en mantenimiento de equipos automatizados' },
    { id: '8', description: 'Aplicar inteligencia artificial en control de sistemas' },
    { id: '9', description: 'Colaborar con ingenieros de distintas áreas' },
    { id: '10', description: 'Investigar innovaciones tecnológicas en robótica' },
  ],
},
{
  name: 'Imagen y sonido',
  activities: [
    { id: '1', description: 'Grabar, editar y producir material audiovisual' },
    { id: '2', description: 'Diseñar la iluminación y el sonido de producciones' },
    { id: '3', description: 'Usar software de edición de video y audio' },
    { id: '4', description: 'Crear bandas sonoras y efectos sonoros' },
    { id: '5', description: 'Controlar equipos técnicos en grabaciones' },
    { id: '6', description: 'Diseñar la estética visual de proyectos multimedia' },
    { id: '7', description: 'Coordinar la postproducción audiovisual' },
    { id: '8', description: 'Trabajar en cine, televisión o publicidad' },
    { id: '9', description: 'Crear videos institucionales o educativos' },
    { id: '10', description: 'Investigar nuevas tecnologías audiovisuales' },
  ],
},
{
  name: 'Minas, petróleo y metalurgia',
  activities: [
    { id: '1', description: 'Supervisar procesos de extracción de minerales y petróleo' },
    { id: '2', description: 'Analizar la composición de minerales y metales' },
    { id: '3', description: 'Diseñar métodos seguros de extracción y refinamiento' },
    { id: '4', description: 'Optimizar la producción en minas o refinerías' },
    { id: '5', description: 'Trabajar en exploración geológica y prospección' },
    { id: '6', description: 'Controlar la calidad de materiales metálicos' },
    { id: '7', description: 'Implementar medidas de seguridad industrial' },
    { id: '8', description: 'Gestionar residuos y minimizar el impacto ambiental' },
    { id: '9', description: 'Asesorar a empresas mineras y energéticas' },
    { id: '10', description: 'Participar en proyectos de desarrollo energético sostenible' },
  ],
},
{
  name: 'Ingeniería industrial',
  activities: [
    { id: '1', description: 'Optimizar procesos productivos y de servicios' },
    { id: '2', description: 'Diseñar sistemas de gestión de calidad y eficiencia' },
    { id: '3', description: 'Analizar tiempos y movimientos en la producción' },
    { id: '4', description: 'Supervisar la logística y el control de inventarios' },
    { id: '5', description: 'Aplicar técnicas de mejora continua' },
    { id: '6', description: 'Evaluar costos y presupuestos operativos' },
    { id: '7', description: 'Gestionar proyectos industriales y tecnológicos' },
    { id: '8', description: 'Implementar normas de seguridad y ergonomía' },
    { id: '9', description: 'Diseñar estrategias de sostenibilidad industrial' },
    { id: '10', description: 'Coordinar equipos interdisciplinarios de producción' },
  ],
},
{
  name: 'Física',
  activities: [
    { id: '1', description: 'Investigar las leyes del universo y sus fenómenos' },
    { id: '2', description: 'Realizar experimentos y análisis de datos físicos' },
    { id: '3', description: 'Modelar sistemas naturales y tecnológicos' },
    { id: '4', description: 'Aplicar la física en ingeniería y tecnología' },
    { id: '5', description: 'Desarrollar teorías y simulaciones científicas' },
    { id: '6', description: 'Trabajar en laboratorios o centros de investigación' },
    { id: '7', description: 'Diseñar instrumentos y equipos de medición' },
    { id: '8', description: 'Aplicar la física en medicina o energía' },
    { id: '9', description: 'Enseñar física en niveles secundarios o universitarios' },
    { id: '10', description: 'Publicar resultados en revistas científicas' },
  ],
},
{
  name: 'Matemáticas aplicadas',
  activities: [
    { id: '1', description: 'Resolver problemas prácticos mediante modelos matemáticos' },
    { id: '2', description: 'Analizar datos y elaborar predicciones estadísticas' },
    { id: '3', description: 'Desarrollar algoritmos para distintos campos' },
    { id: '4', description: 'Aplicar matemáticas en economía, física o biología' },
    { id: '5', description: 'Optimizar procesos industriales y logísticos' },
    { id: '6', description: 'Colaborar en proyectos de investigación científica' },
    { id: '7', description: 'Desarrollar software matemático y de simulación' },
    { id: '8', description: 'Trabajar en análisis financiero o de riesgo' },
    { id: '9', description: 'Aplicar estadística avanzada en investigación' },
    { id: '10', description: 'Enseñar matemáticas aplicadas en instituciones educativas' },
  ],
},
{
  name: 'Ingeniería en estadística',
  activities: [
    { id: '1', description: 'Recolectar y analizar datos de distintos sectores' },
    { id: '2', description: 'Diseñar encuestas y experimentos estadísticos' },
    { id: '3', description: 'Elaborar modelos predictivos y de probabilidad' },
    { id: '4', description: 'Trabajar en control de calidad y mejora de procesos' },
    { id: '5', description: 'Interpretar información para toma de decisiones empresariales' },
    { id: '6', description: 'Programar en software estadístico (R, Python, SPSS, etc.)' },
    { id: '7', description: 'Asesorar en proyectos de investigación cuantitativa' },
    { id: '8', description: 'Visualizar datos para comunicación de resultados' },
    { id: '9', description: 'Trabajar en estudios de mercado y opinión pública' },
    { id: '10', description: 'Aplicar métodos estadísticos en biología, economía o ingeniería' },
  ],
},
{
  name: 'Ingeniería automotriz',
  activities: [
    { id: '1', description: 'Diseñar y desarrollar vehículos y sistemas automotrices' },
    { id: '2', description: 'Analizar y mejorar el rendimiento de motores y componentes' },
    { id: '3', description: 'Realizar pruebas de seguridad y eficiencia energética' },
    { id: '4', description: 'Supervisar procesos de fabricación automotriz' },
    { id: '5', description: 'Aplicar tecnología de control y electrónica en vehículos' },
    { id: '6', description: 'Investigar materiales y técnicas de producción innovadoras' },
    { id: '7', description: 'Colaborar en diseño de vehículos eléctricos o autónomos' },
    { id: '8', description: 'Optimizar procesos de mantenimiento y reparación' },
    { id: '9', description: 'Analizar normativas de seguridad y emisiones' },
    { id: '10', description: 'Trabajar en investigación y desarrollo de nuevas tecnologías automotrices' },
  ],
},
{
  name: 'Biotecnología ambiental',
  activities: [
    { id: '1', description: 'Desarrollar soluciones biotecnológicas para problemas ambientales' },
    { id: '2', description: 'Analizar muestras de agua, suelo y aire' },
    { id: '3', description: 'Diseñar procesos de tratamiento de residuos y contaminantes' },
    { id: '4', description: 'Aplicar técnicas de ingeniería genética y microbiología' },
    { id: '5', description: 'Monitorear la biodiversidad y ecosistemas' },
    { id: '6', description: 'Investigar energías renovables y sostenibles' },
    { id: '7', description: 'Colaborar con organismos ambientales y empresas privadas' },
    { id: '8', description: 'Realizar estudios de impacto ambiental' },
    { id: '9', description: 'Diseñar proyectos de bioremediación y conservación' },
    { id: '10', description: 'Publicar investigaciones y proponer políticas ambientales' },
  ],
},
{
  name: 'Ingeniería geográfica',
  activities: [
    { id: '1', description: 'Analizar y representar información geográfica y territorial' },
    { id: '2', description: 'Desarrollar mapas y sistemas de información geográfica (SIG)' },
    { id: '3', description: 'Realizar estudios de planificación urbana y territorial' },
    { id: '4', description: 'Supervisar proyectos de cartografía y geodesia' },
    { id: '5', description: 'Aplicar tecnologías de teledetección y GPS' },
    { id: '6', description: 'Colaborar en gestión de recursos naturales y riesgos ambientales' },
    { id: '7', description: 'Analizar datos geográficos para proyectos de infraestructura' },
    { id: '8', description: 'Participar en investigaciones geográficas y climáticas' },
    { id: '9', description: 'Elaborar informes técnicos y mapas especializados' },
    { id: '10', description: 'Asesorar a gobiernos y empresas en planificación territorial' },
  ],
},
{
  name: 'Carreras militares (marina, aviación, ejército)',
  activities: [
    { id: '1', description: 'Participar en operaciones y maniobras militares' },
    { id: '2', description: 'Planificar estrategias de defensa y seguridad' },
    { id: '3', description: 'Capacitar y liderar a personal militar' },
    { id: '4', description: 'Mantener y supervisar equipos y tecnología militar' },
    { id: '5', description: 'Desarrollar protocolos de entrenamiento físico y táctico' },
    { id: '6', description: 'Colaborar en misiones de ayuda humanitaria y rescate' },
    { id: '7', description: 'Aplicar técnicas de inteligencia y logística militar' },
    { id: '8', description: 'Cumplir con normas y reglamentos de seguridad y disciplina' },
    { id: '9', description: 'Participar en planificación de misiones internacionales' },
    { id: '10', description: 'Desarrollar liderazgo y toma de decisiones bajo presión' },
  ],
},
{
  name: 'Ingeniería en costas y obras portuarias',
  activities: [
    { id: '1', description: 'Diseñar y supervisar puertos, muelles y obras costeras' },
    { id: '2', description: 'Analizar corrientes, mareas y erosión costera' },
    { id: '3', description: 'Planificar la infraestructura marítima y logística portuaria' },
    { id: '4', description: 'Aplicar normas de seguridad y sostenibilidad en obras marítimas' },
    { id: '5', description: 'Supervisar construcción y mantenimiento de obras civiles en costas' },
    { id: '6', description: 'Realizar estudios de impacto ambiental en zonas costeras' },
    { id: '7', description: 'Colaborar con ingenieros navales y urbanistas' },
    { id: '8', description: 'Gestionar proyectos de dragado y protección costera' },
    { id: '9', description: 'Usar software de modelado y simulación hidráulica' },
    { id: '10', description: 'Asesorar a autoridades portuarias y marítimas' },
  ],
},
{
  name: 'Estadística informática',
  activities: [
    { id: '1', description: 'Analizar grandes volúmenes de datos usando software estadístico' },
    { id: '2', description: 'Desarrollar modelos predictivos y de análisis de datos' },
    { id: '3', description: 'Programar algoritmos y herramientas estadísticas' },
    { id: '4', description: 'Interpretar resultados para la toma de decisiones' },
    { id: '5', description: 'Visualizar datos para comunicar hallazgos efectivamente' },
    { id: '6', description: 'Optimizar bases de datos y procesos de cálculo' },
    { id: '7', description: 'Colaborar en investigación científica y tecnológica' },
    { id: '8', description: 'Aplicar técnicas de minería de datos e inteligencia artificial' },
    { id: '9', description: 'Validar modelos y resultados estadísticos' },
    { id: '10', description: 'Asesorar empresas o instituciones en análisis cuantitativo' },
  ],
},
{
  name: 'Programación y desarrollo de sistemas',
  activities: [
    { id: '1', description: 'Diseñar, codificar y mantener software y aplicaciones' },
    { id: '2', description: 'Analizar requerimientos de usuarios y sistemas' },
    { id: '3', description: 'Implementar bases de datos y estructuras de información' },
    { id: '4', description: 'Probar, depurar y optimizar programas y algoritmos' },
    { id: '5', description: 'Documentar proyectos y procedimientos de desarrollo' },
    { id: '6', description: 'Colaborar con equipos de diseño y testers' },
    { id: '7', description: 'Aplicar metodologías ágiles de desarrollo de software' },
    { id: '8', description: 'Actualizar sistemas según nuevas tecnologías y estándares' },
    { id: '9', description: 'Asegurar la seguridad y estabilidad de aplicaciones' },
    { id: '10', description: 'Investigar y aplicar nuevas tendencias en desarrollo de software' },
  ],
},
{
  name: 'Tecnología en informática educativa',
  activities: [
    { id: '1', description: 'Diseñar e implementar herramientas tecnológicas para la educación' },
    { id: '2', description: 'Capacitar docentes en el uso de recursos digitales' },
    { id: '3', description: 'Desarrollar plataformas educativas interactivas' },
    { id: '4', description: 'Integrar software y hardware en entornos de aprendizaje' },
    { id: '5', description: 'Analizar el impacto de la tecnología en el aprendizaje' },
    { id: '6', description: 'Actualizar contenidos educativos digitales' },
    { id: '7', description: 'Evaluar la accesibilidad y usabilidad de recursos tecnológicos' },
    { id: '8', description: 'Colaborar con instituciones educativas en proyectos digitales' },
    { id: '9', description: 'Implementar soluciones de educación a distancia y e-learning' },
    { id: '10', description: 'Investigar nuevas metodologías educativas basadas en tecnología' },
  ],
},
{
  name: 'Astronomía',
  activities: [
    { id: '1', description: 'Estudiar cuerpos celestes y fenómenos astronómicos' },
    { id: '2', description: 'Realizar observaciones con telescopios y satélites' },
    { id: '3', description: 'Analizar datos de luz, gravedad y movimientos planetarios' },
    { id: '4', description: 'Desarrollar modelos del universo y simulaciones astronómicas' },
    { id: '5', description: 'Investigar estrellas, planetas, galaxias y agujeros negros' },
    { id: '6', description: 'Colaborar en proyectos de exploración espacial' },
    { id: '7', description: 'Publicar resultados científicos y teorías astronómicas' },
    { id: '8', description: 'Trabajar en observatorios, planetarios o centros de investigación' },
    { id: '9', description: 'Divulgar conocimientos de astronomía al público general' },
    { id: '10', description: 'Aplicar técnicas de física y matemáticas en estudios astronómicos' },
  ],
},
{
  name: 'Ingeniería en ciencias geográficas y desarrollo sustentable',
  activities: [
    { id: '1', description: 'Analizar el uso del suelo y planificación territorial' },
    { id: '2', description: 'Desarrollar proyectos de desarrollo urbano y rural sostenibles' },
    { id: '3', description: 'Gestionar recursos naturales y protección ambiental' },
    { id: '4', description: 'Implementar tecnologías geográficas y SIG en proyectos' },
    { id: '5', description: 'Evaluar impacto ambiental y social de proyectos' },
    { id: '6', description: 'Colaborar con gobiernos y empresas en planificación sustentable' },
    { id: '7', description: 'Diseñar estrategias de mitigación de riesgos naturales' },
    { id: '8', description: 'Realizar estudios de geografía física y humana' },
    { id: '9', description: 'Elaborar informes técnicos y mapas especializados' },
    { id: '10', description: 'Promover prácticas sostenibles en comunidades y empresas' },
  ],
},

  ],
  'V': [
    {
      name: 'Medicina',
      activities: [
        { id: '1', description: 'Examinar pacientes y diagnosticar enfermedades' },
        { id: '2', description: 'Prescribir medicamentos y tratamientos' },
        { id: '3', description: 'Realizar procedimientos médicos' },
        { id: '4', description: 'Hacer seguimiento de evolución del paciente' },
        { id: '5', description: 'Derivar a especialistas cuando sea necesario' },
        { id: '6', description: 'Mantenerse actualizado con avances médicos' },
        { id: '7', description: 'Trabajar bajo presión' },
        { id: '8', description: 'Comunicarse empáticamente con pacientes' },
        { id: '9', description: 'Documentar historiales médicos' },
        { id: '10', description: 'Trabajar horarios irregulares' },
      ],
    },
    {
      name: 'Enfermería',
      activities: [
        { id: '1', description: 'Administrar medicamentos a pacientes' },
        { id: '2', description: 'Cambiar vendajes y hacer curaciones' },
        { id: '3', description: 'Monitorear signos vitales' },
        { id: '4', description: 'Proporcionar cuidado personal a pacientes' },
        { id: '5', description: 'Colaborar con equipo médico' },
        { id: '6', description: 'Registrar información de pacientes' },
        { id: '7', description: 'Proporcionar apoyo emocional' },
        { id: '8', description: 'Trabajar en ambiente hospitalario o clínico' },
        { id: '9', description: 'Seguir protocolos de higiene' },
        { id: '10', description: 'Estar disponible en turnos diversos' },
      ],
    },
    {
      name: 'Odontología',
      activities: [
        { id: '1', description: 'Examinar cavidades bucales de pacientes' },
        { id: '2', description: 'Limpiar y remover sarro de dientes' },
        { id: '3', description: 'Extraer dientes dañados' },
        { id: '4', description: 'Colocar empastes y coronas' },
        { id: '5', description: 'Hacer radiografías dentales' },
        { id: '6', description: 'Tratar infecciones dentales' },
        { id: '7', description: 'Enseñar higiene bucal a pacientes' },
        { id: '8', description: 'Usar herramientas odontológicas especializadas' },
        { id: '9', description: 'Mantener consultorios higienizados' },
        { id: '10', description: 'Trabajar meticulosamente en espacios pequeños' },
      ],
    },
    {
      name: 'Veterinaria',
      activities: [
        { id: '1', description: 'Examinar animales enfermos' },
        { id: '2', description: 'Prescribir medicamentos veterinarios' },
        { id: '3', description: 'Hacer cirugías animales' },
        { id: '4', description: 'Vacunar y esterilizar animales' },
        { id: '5', description: 'Hacer diagnósticos por imagen' },
        { id: '6', description: 'Educar a dueños sobre cuidado animal' },
        { id: '7', description: 'Trabajar con animales en diferentes condiciones' },
        { id: '8', description: 'Manejar emergencias veterinarias' },
        { id: '9', description: 'Mantener equipamiento veterinario' },
        { id: '10', description: 'Mostrar compasión por los animales' },
      ],
    },
    {
      name: 'Nutrición',
      activities: [
        { id: '1', description: 'Evaluar hábitos alimenticios de pacientes' },
        { id: '2', description: 'Diseñar planes nutricionales personalizados' },
        { id: '3', description: 'Hacer seguimiento de peso y cambios' },
        { id: '4', description: 'Educar sobre alimentación saludable' },
        { id: '5', description: 'Trabajar con pacientes con condiciones especiales' },
        { id: '6', description: 'Investigar nuevas dietas y técnicas' },
        { id: '7', description: 'Colaborar con médicos' },
        { id: '8', description: 'Usar software de análisis nutricional' },
        { id: '9', description: 'Mantener registros de pacientes' },
        { id: '10', description: 'Motivar cambios de estilo de vida' },
      ],
    },
    {
      name: 'Biología',
      activities: [
        { id: '1', description: 'Conducir experimentos en laboratorio' },
        { id: '2', description: 'Observar y catalogar organismos' },
        { id: '3', description: 'Analizar muestras biológicas' },
        { id: '4', description: 'Investigar procesos biológicos' },
        { id: '5', description: 'Documentar hallazgos científicos' },
        { id: '6', description: 'Usar microscopios y equipamiento especializado' },
        { id: '7', description: 'Colaborar en equipos de investigación' },
        { id: '8', description: 'Publicar resultados de estudios' },
        { id: '9', description: 'Enseñar biología a estudiantes' },
        { id: '10', description: 'Contribuir a avances científicos' },
      ],
    },
    {
      name: 'Farmacia',
      activities: [
        { id: '1', description: 'Dispensar medicamentos a pacientes' },
        { id: '2', description: 'Asesorar sobre uso correcto de fármacos' },
        { id: '3', description: 'Verificar interacciones medicamentosas' },
        { id: '4', description: 'Gestionar inventario de medicinas' },
        { id: '5', description: 'Colaborar con prescriptores' },
        { id: '6', description: 'Mantener farmacias organizadas' },
        { id: '7', description: 'Educar sobre efectos secundarios' },
        { id: '8', description: 'Cumplir regulaciones farmacéuticas' },
        { id: '9', description: 'Atender consultas de pacientes' },
        { id: '10', description: 'Participar en investigación farmacéutica' },
      ],
    },
    {
      name: 'Ciencias ambientales',
      activities: [
        { id: '1', description: 'Monitorear calidad del aire y agua' },
        { id: '2', description: 'Hacer estudios de impacto ambiental' },
        { id: '3', description: 'Proponer soluciones de sostenibilidad' },
        { id: '4', description: 'Investigar cambio climático' },
        { id: '5', description: 'Colaborar con gobiernos y ONGs' },
        { id: '6', description: 'Hacer trabajo de campo' },
        { id: '7', description: 'Usar instrumentación especializada' },
        { id: '8', description: 'Analizar datos ambientales' },
        { id: '9', description: 'Educar sobre conservación' },
        { id: '10', description: 'Defender recursos naturales' },
      ],
    },
    {
      name: 'Zootecnia',
      activities: [
        { id: '1', description: 'Gestionar criaderos de animales' },
        { id: '2', description: 'Mejorar genética de razas' },
        { id: '3', description: 'Controlar nutrición animal' },
        { id: '4', description: 'Prevenir enfermedades ganaderas' },
        { id: '5', description: 'Hacer reproducción asistida' },
        { id: '6', description: 'Registrar datos de productividad' },
        { id: '7', description: 'Trabajar en campo y granjas' },
        { id: '8', description: 'Usar tecnología agrícola moderna' },
        { id: '9', description: 'Asesorar a ganaderos' },
        { id: '10', description: 'Mejorar bienestar animal' },
      ],
    },
    {
      name: 'Agronomía',
      activities: [
        { id: '1', description: 'Diseñar planes de cultivo' },
        { id: '2', description: 'Analizar suelos y propiedades' },
        { id: '3', description: 'Controlar plagas y enfermedades' },
        { id: '4', description: 'Seleccionar semillas y variedades' },
        { id: '5', description: 'Optimizar riego y fertilización' },
        { id: '6', description: 'Hacer trabajo de campo' },
        { id: '7', description: 'Usar maquinaria agrícola' },
        { id: '8', description: 'Investigar técnicas sostenibles' },
        { id: '9', description: 'Asesorar agricultores' },
        { id: '10', description: 'Mejorar rendimiento de cultivos' },
      ],
    },
    {
      name: 'Gastronomía',
      activities: [
        { id: '1', description: 'Crear y diseñar menús' },
        { id: '2', description: 'Preparar platos con técnicas especializadas' },
        { id: '3', description: 'Combinar sabores e ingredientes' },
        { id: '4', description: 'Supervisar cocina y equipo' },
        { id: '5', description: 'Trabajar bajo presión en horas pico' },
        { id: '6', description: 'Capacitar a otros cocineros' },
        { id: '7', description: 'Controlar costos de ingredientes' },
        { id: '8', description: 'Investigar nuevas recetas' },
        { id: '9', description: 'Mantener estándares de higiene' },
        { id: '10', description: 'Satisfacer paladares de clientes' },
      ],
    },
  ],
};