// lib/questions.ts

export interface Question {
  id: number;
  text: string;
  area: 'I' | 'II' | 'III' | 'IV' | 'V';
}

export const QUESTIONS: Question[] = [
  { id: 1, text: 'Diseñar programas de computación y explorar nuevas aplicaciones tecnológicas para uso del internet.', area: 'IV' },
  { id: 2, text: 'Criar, cuidar y tratar animales domésticos y de campo.', area: 'V' },
  { id: 3, text: 'Investigar sobre áreas verdes, medioambiente y cambios climáticos.', area: 'V' },
  { id: 4, text: 'Ilustrar, dibujar y animar digitalmente.', area: 'I' },
  { id: 5, text: 'Seleccionar, capacitar y motivar al personal de una organización o empresa.', area: 'III' },
  { id: 6, text: 'Realizar excavaciones para descubrir restos del pasado.', area: 'II' },
  { id: 7, text: 'Resolver problemas de cálculo para construir un puente.', area: 'IV' },
  { id: 8, text: 'Diseñar cursos para enseñar a la gente sobre temas de salud e higiene.', area: 'V' },
  { id: 9, text: 'Tocar un instrumento y componer música.', area: 'I' },
  { id: 10, text: 'Planificar cuáles son las metas de una organización pública o privada a mediano y largo plazo.', area: 'III' },
  { id: 11, text: 'Diseñar y planificar la producción masiva de artículos como muebles, autos, equipos de oficina, empaques y envases para alimentos y otros.', area: 'IV' },
  { id: 12, text: 'Diseñar logotipos y portadas de una revista.', area: 'I' },
  { id: 13, text: 'Organizar eventos y atender a sus asistentes.', area: 'II' },
  { id: 14, text: 'Atender la salud de personas enfermas.', area: 'V' },
  { id: 15, text: 'Controlar ingresos y egresos de fondos y presentar el balance final de una institución.', area: 'III' },
  { id: 16, text: 'Hacer experimentos con plantas (frutas, árboles, flores).', area: 'V' },
  { id: 17, text: 'Concebir planos para viviendas, edificios y ciudadelas.', area: 'IV' },
  { id: 18, text: 'Investigar y probar nuevos productos farmacéuticos.', area: 'V' },
  { id: 19, text: 'Hacer propuestas y formular estrategias para aprovechar las relaciones económicas entre dos países.', area: 'III' },
  { id: 20, text: 'Pintar, hacer esculturas, ilustrar libros de arte, etcétera.', area: 'I' },
  { id: 21, text: 'Elaborar campañas para introducir un nuevo producto al mercado.', area: 'III' },
  { id: 22, text: 'Examinar y tratar los problemas visuales.', area: 'V' },
  { id: 23, text: 'Defender a clientes individuales o empresas en juicios de diferente naturaleza.', area: 'II' },
  { id: 24, text: 'Diseñar máquinas que puedan simular actividades humanas.', area: 'IV' },
  { id: 25, text: 'Investigar las causas y efectos de los trastornos emocionales.', area: 'II' },
  { id: 26, text: 'Supervisar las ventas de un centro comercial.', area: 'III' },
  { id: 27, text: 'Atender y realizar ejercicios a personas que tienen limitaciones físicas, problemas de lenguaje, etc.', area: 'V' },
  { id: 28, text: 'Prepararse para ser modelo profesional.', area: 'I' },
  { id: 29, text: 'Aconsejar a las personas sobre planes de ahorro e inversiones.', area: 'III' },
  { id: 30, text: 'Elaborar mapas, planos e imágenes para el estudio y análisis de datos geográficos.', area: 'IV' },
  { id: 31, text: 'Diseñar juegos interactivos electrónicos para computadora.', area: 'I' },
  { id: 32, text: 'Realizar el control de calidad de los alimentos.', area: 'V' },
  { id: 33, text: 'Tener un negocio propio de tipo comercial.', area: 'III' },
  { id: 34, text: 'Escribir artículos periodísticos, cuentos, novelas y otros.', area: 'II' },
  { id: 35, text: 'Redactar guiones y libretos para un programa de televisión.', area: 'I' },
  { id: 36, text: 'Organizar un plan de distribución y venta de un gran almacén.', area: 'III' },
  { id: 37, text: 'Estudiar la diversidad cultural en el ámbito rural y urbano.', area: 'II' },
  { id: 38, text: 'Gestionar y evaluar convenios internacionales de cooperación para el desarrollo social.', area: 'II' },
  { id: 39, text: 'Crear campañas publicitarias.', area: 'I' },
  { id: 40, text: 'Trabajar investigando la reproducción de peces, camarones y otros animales marinos.', area: 'V' },
  { id: 41, text: 'Dedicarse a fabricar productos alimenticios de consumo masivo.', area: 'IV' },
  { id: 42, text: 'Gestionar y evaluar proyectos de desarrollo en una institución educativa y/o fundación.', area: 'II' },
  { id: 43, text: 'Rediseñar y decorar espacios físicos en viviendas, oficinas y locales comerciales.', area: 'I' },
  { id: 44, text: 'Administrar una empresa de turismo o agencias de viaje.', area: 'III' },
  { id: 45, text: 'Aplicar métodos alternativos a la medicina tradicional, para atender personas con dolencias de diversa índole.', area: 'V' },
  { id: 46, text: 'Diseñar ropa para niños, jóvenes y adultos.', area: 'I' },
  { id: 47, text: 'Investigar organismos vivos para elaborar vacunas.', area: 'V' },
  { id: 48, text: 'Manejar o hacerle mantenimiento a dispositivos tecnológicos en aviones, barcos, radares, etc.', area: 'IV' },
  { id: 49, text: 'Estudiar idiomas extranjeros —actuales y antiguos— para hacer traducción.', area: 'II' },
  { id: 50, text: 'Restaurar piezas y obras de arte.', area: 'I' },
  { id: 51, text: 'Revisar y dar mantenimiento a artefactos eléctricos, electrónicos y computadoras.', area: 'IV' },
  { id: 52, text: 'Enseñar a niños de cero a cinco años.', area: 'II' },
  { id: 53, text: 'Investigar o sondear nuevos mercados.', area: 'III' },
  { id: 54, text: 'Atender la salud dental de las personas.', area: 'V' },
  { id: 55, text: 'Tratar a niños, jóvenes y adultos con problemas psicológicos.', area: 'II' },
  { id: 56, text: 'Crear estrategias de promoción y venta de nuevos productos nacionales en el mercado internacional.', area: 'III' },
  { id: 57, text: 'Planificar y recomendar dietas para personas diabéticas o con sobrepeso.', area: 'V' },
  { id: 58, text: 'Trabajar en una empresa petrolera en un cargo técnico como control de la producción.', area: 'IV' },
  { id: 59, text: 'Administrar una empresa (familiar, privada o pública).', area: 'III' },
  { id: 60, text: 'Tener un taller de reparación y mantenimiento de carros, tractores, etcétera.', area: 'IV' },
  { id: 61, text: 'Ejecutar proyectos de extracción minera y metalúrgica.', area: 'IV' },
  { id: 62, text: 'Asistir a directivos de multinacionales con manejo de varios idiomas.', area: 'III' },
  { id: 63, text: 'Diseñar programas educativos para niños con discapacidad.', area: 'II' },
  { id: 64, text: 'Aplicar conocimientos de estadística en investigaciones en diversas áreas (social, administrativa, salud, etcétera.).', area: 'IV' },
  { id: 65, text: 'Fotografiar hechos históricos, lugares significativos, rostros, paisajes para el área publicitaria, artística, periodística y social.', area: 'I' },
  { id: 66, text: 'Trabajar en museos y bibliotecas nacionales e internacionales.', area: 'II' },
  { id: 67, text: 'Ser parte de un grupo de teatro.', area: 'I' },
  { id: 68, text: 'Producir cortometrajes, spots publicitarios, programas educativos, de ficción, etc.', area: 'I' },
  { id: 69, text: 'Estudiar la influencia entre las corrientes marinas y el clima y sus consecuencias ecológicas.', area: 'V' },
  { id: 70, text: 'Conocer las distintas religiones (su filosofía) y transmitirlas a la comunidad en general.', area: 'II' },
  { id: 71, text: 'Asesorar a inversionistas en la compra de bienes y acciones en mercados nacionales e internacionales.', area: 'III' },
  { id: 72, text: 'Estudiar grupos étnicos, sus costumbres, tradiciones, cultura y compartir sus vivencias.', area: 'II' },
  { id: 73, text: 'Explorar el espacio sideral, los planetas, características y componentes.', area: 'IV' },
  { id: 74, text: 'Mejorar la imagen facial y corporal de las personas, aplicando diferentes técnicas.', area: 'V' },
  { id: 75, text: 'Decorar jardines de casas y parques públicos.', area: 'I' },
  { id: 76, text: 'Administrar y renovar menús de comidas en un hotel o restaurante.', area: 'V' },
  { id: 77, text: 'Trabajar como presentador de televisión, locutor de radio y televisión, animador de programas culturales y concursos.', area: 'I' },
  { id: 78, text: 'Diseñar y ejecutar programas de turismo.', area: 'II' },
  { id: 79, text: 'Administrar y ordenar (planificar) adecuadamente la ocupación del espacio físico de ciudades, países etc., utilizando imágenes de satélite, mapas.', area: 'IV' },
  { id: 80, text: 'Organizar, planificar y administrar centros educativos.', area: 'III' },
];