import type { ActivityDefinition } from '@/types/activity';

export const ACTIVITIES: ActivityDefinition[] = [
  {
    id: "trivias",
    title: "Trivias",
    description: "Poné a prueba tus conocimientos jugando trivias sobre salud, derechos, diversidad y mucho más.",
    route: "/trivias",
    color: "#1976D2",
    image: "/trivia.svg",
    category: "Evaluación",
    iconName: "IconCards",
    priority: true,
  },
  {
    id: "pasapalabras",
    title: "Pasapalabras",
    description: "Jugá con las letras del abecedario y descubrí palabras claves a partir de sus definiciones.",
    route: "/pasapalabras",
    color: "#388E3C",
    image: "/pasapalabras.svg",
    category: "Ejercicios",
    iconName: "IconAB2",
    priority: true,
  },
  {
    id: "simulador",
    title: "Simulador Grooming",
    description: "Practicá cómo reaccionar ante mensajes sospechosos y aprendé a cuidarte en las redes sociales.",
    route: "/simulador",
    color: "#F57C00",
    image: "/simulador.svg",
    category: "Seguridad",
    iconName: "IconShieldCheck",
    priority: true,
  },
  {
    id: "completa",
    title: "Completa Palabras",
    description: "Completá frases con las palabras correctas y descubrí conceptos sobre sexualidad, cuidado y derechos.",
    route: "/completapalabras",
    color: "#7B1FA2",
    image: "/completa.svg",
    category: "Ejercicios",
    iconName: "IconBrandPnpm",
  },
  {
    id: "datamuncher",
    title: "DataMuncher",
    description: "Recorré el laberinto, respondé preguntas y esquivá bacterias para sumar puntos así ganar el juego.",
    route: "/datamuncher",
    color: "#D32F2F",
    image: "/datamuncher.svg",
    category: "Juegos Educativos",
    iconName: "IconPacman",
  },
  {
    id: "moodtracker",
    title: "MoodTracker",
    description: "Reflexioná sobre cómo te sentís, registrá tus emociones y aprendé a expresar tu estado de ánimo.",
    route: "/moodtracker",
    color: "#0288D1",
    image: "/moodtracker.svg",
    category: "Bienestar",
    iconName: "IconMoodPuzzled",
  },
  {
    id: "meme",
    title: "Meme Generator",
    description: "Creá memes originales con mensajes reflexivos y compartilos con tus amistades.",
    route: "/memegenerador",
    color: "#689F38",
    image: "/meme.svg",
    category: "Creatividad",
    iconName: "IconMoodTongueWink2",
  },
  {
    id: "literatura",
    title: "Literatura",
    description: "Leé cuentos breves y relatos que invitan a reflexionar sobre vínculos, derechos y emociones.",
    route: "/literatura",
    color: "#F57C00",
    image: "/literatura.svg",
    category: "Lectura",
    iconName: "IconBook",
  },
  {
    id: "biopuzzle",
    title: "BioPuzzle",
    description: "Completá el rompecabezas de la biología humana y aprendé sobre el cuerpo humano de forma divertida.",
    route: "/biopuzzle",
    color: "#7B1FA2",
    image: "/biopluzzle.svg",
    category: "Lectura",
    iconName: "IconMoodPuzzled",
    iconSize: 24,
  },
  {
    id: "condon",
    title: "Prevención",
    description: "Todo sobre el preservativo, el único método que reduce la posibilidad de contraer un ITS.",
    route: "/condon",
    color: "#D32F2F",
    image: "/condon.svg",
    category: "Lectura",
    iconName: "IconMoodPuzzled",
    iconSize: 24,
  },
  {
    id: "lecciones",
    title: "Lecciones",
    description: "Poné a prueba tus conocimientos jugando trivias sobre salud, derechos, diversidad y mucho más.",
    route: "/lecciones",
    color: "#1976D2",
    image: "/trivia.svg",
    category: "Lectura",
    iconName: "IconCards",
    priority: true,
  },
  {
    id: "saludmental",
    title: "Salud Mental Test",
    description: "Evaluá tu estado emocional y recibí orientación sobre bienestar mental con nuestro test interactivo.",
    route: "/saludmental",
    color: "#388E3C",
    image: "/saludmental.svg",
    category: "Ejercicios",
    iconName: "IconHeart",
    priority: true,
  },
  {
    id: "vocacion",
    title: "Test Vocacional",
    description: "Descubrí carreras y profesiones que se alinean con tus intereses y habilidades mediante nuestro test vocacional.",
    route: "/vocacion",
    color: "#388E3C",
    image: "/vocacion.svg",
    category: "Ejercicios",
    iconName: "IconBrandPnpm",
    priority: true,
  },
  {
    id: "amor",
    title: "Amor Sin Violencia",
    description: "Aprendé a detectar señales de violencias en tus relaciones de pareja o amistades.",
    route: "/amor",
    color: "#F57C00",
    image: "/completa.svg",
    category: "Ejercicios",
    iconName: "IconHeart",
  },
  {
    id: "impostor",
    title: "Impostor",
    description: "Descubrí quién es el impostor mientras aprendés sobre el sexualidad, cuerpo humano y la biología.",
    route: "/impostor",
    color: "#7B1FA2",
    image: "/biopluzzle.svg",
    category: "Juegos Educativos",
    iconName: "IconMoodPuzzled",
    iconSize: 24,
  },
  {
    id: "buscador",
    title: "Buscador de Preguntas",
    description: "Buscá entre nuestro banco de preguntas sobre ESI por palabra clave.",
    route: "/buscador",
    color: "#4F46E5",
    image: "/trivia.svg",
    category: "Evaluación",
    iconName: "IconSearch",
  },
  {
    id: "infografias",
    title: "Infografías",
    description: "Material visual educativo sobre salud, sexualidad y relaciones saludables, para consultar y descargar.",
    route: "/infografias",
    color: "#00897B",
    image: "/trivia.svg",
    category: "Lectura",
    iconName: "IconPhoto",
  },
];

/** Solo los ids, en el mismo orden — para defaults de visibilidad/orden del dashboard. */
export const ACTIVITY_IDS = ACTIVITIES.map((a) => a.id);

export function getActivityById(id: string): ActivityDefinition | undefined {
  return ACTIVITIES.find((a) => a.id === id);
}